export const categoriesEn = [
    'Car', 'Tree', 'Trash can', 'Window', 'Door', 'Storefront', 'Bicycle', 
    'Bench', 'Mailbox', 'Bus stop', 'Tram', 'Pedestrian crossing', 
    'Parking meter', 'Cell phone', 'Dog', 'Cat', 'Person', 'Stroller', 
    'Shopping bag', 'Umbrella', 'Jacket', 'Hat', 'Glasses', 'Backpack', 
    'Suitcase', 'Cart', 'Truck', 'Bus', 'Police car', 'Fire engine', 
    'Bakery', 'Supermarket', 'Pharmacy', 'Bank building', 'Restaurant', 
    'Cafe', 'Dentist', 'Hairdresser', 'Flower shop', 'Bookstore', 
    'Movie theater', 'Theater', 'Hotel', 'Car dealership', 'Gas station', 
    'Car wash', 'School', 'Kindergarten', 'Church', 'Mosque', 'Garden', 
    'Fence', 'Gate', 'Chair', 'Table', 'Flower pot', 'Flag', 'Poster', 
    'Graffiti', 'Cell phone store', 'Boutique', 'Shoe store', 'Sports shop', 
    'Drugstore', 'Post office', 'Telephone booth', 'Gumball machine', 
    'Newsstand', 'Street musician', 'Jogger', 'Cyclist', 'Skater', 
    'Wheelchair', 'Luggage cart', 'Toolbox', 'Ladder', 'Construction site', 
    'Crane', 'Scaffolding', 'Traffic cone', 'Caution tape', 'Shovel', 
    'Bucket', 'Street broom', 'Street sweeper', 'Leaf', 'Stone', 'Puddle', 
    'Water tap', 'Fire extinguisher', 'Emergency call box', 'Clock', 
    'Thermometer', 'Weather display', 'Stop sign', 'Bridge', 'Tunnel', 
    'Railroad crossing', 'Train tracks', 'Train', 'Street map', 'Bike rack', 
    'EV charging station', 'Sunglasses', 'Sun hat', 'Ice cream stand', 
    'Hot dog stand', 'Sausage stand', 'Beer garden', 'Street festival', 
    'Balloon', 'Trash bin', 'Glass container', 'Paper recycling', 'Parking sign', 
    'Playground', 'Swing', 'Slide', 'Sandbox', 'Jungle gym', 'Traffic light', 
    'One-way street sign', 'No-parking sign', 'Speed limit 30 sign', 
    'No-trucks sign', 'Children sign', 'School bus', 'Directional arrow', 
    '30 km/h zone sign', 'Speed limit 50 sign', 'Paid parking zone', 
    'No-stopping sign', 'Merge sign', 'Exit sign', 'Right turn sign', 
    'Construction ahead sign', 'Right of way sign', 'Zebra crossing', 
    'Bike lane', 'Pedestrian zone', 'Dumpster', 'Street lamp',
    'Unlimited sign', 'Pool', 'Red car', 'Yellow car', 'Green car', 'Blue car', 'White car', 'Black car',
    'Silver car', 'Orange car', 'Purple car', 'Brown car', 'Pink car', 'Gray cars',
    'Tractor', 'Motorcycle', 'Scooter', 'Bus', 'RV', 'Camper van', 'Delivery van',
    'Tram', 'Subway sign', 'Train station sign', 'Ferry', 'Sailboat', 'Yacht', 'Canoe', 
    'Kayak', 'Inflatable boat', 'Steamboat', 'Fishing boat', 
    'Police boat', 'Fire boat', 'Rescue boat', 'Submarine', 'Helicopter', 'Person on phone',
    'Waving person', 'Musician', 'Artist'
];

export const categoriesDe = [
    'Mülltonne', 'Bankgeschäft', 'Briefkasten', 'Bushaltestelle', 'Straßenbahn', 'Fußgängerüberweg', 
    'Parkuhr', 'Hund', 'Katze', 'Mensch', 'Kinderwagen', 
    'Einkaufstasche', 'Regenschirm', 'Jacke', 'Hut', 'Rucksack', 
    'Koffer', 'LKW', 'Bus', 'Polizeiauto', 'Feuerwehr', 
    'Bäckerei', 'Supermarkt', 'Apotheke', 'Bankgebäude', 'Restaurant', 
    'Café', 'Zahnarzt', 'Friseur', 'Blumenladen', 'Buchhandlung', 
    'Kino', 'Theater', 'Hotel', 'Autohaus', 'Tankstelle', 
    'Waschstraße', 'Schule', 'Kindergarten', 'Kirche', 'Moschee', 'Garten', 
    'Zaun', 'Tor', 'Stuhl', 'Tisch', 'Blumentopf', 'Flagge',
    'Graffiti', 'Handy-Laden', 'Schuhgeschäft', 'Sportgeschäft', 
    'Drogerie', 'Post', 'Telefonzelle', 'Kaugummiautomat', 
    'Zeitungskiosk', 'Straßenmusiker', 'Jogger', 'Skater', 
    'Rollstuhl', 'Leiter', 'Baustelle', 
    'Gerüst', 'Verkehrskegel', 'Absperrband', 'Schaufel', 
    'Eimer', 'Blatt', 'Pfütze', 
    'Wasserhahn', 'Feuerlöscher', 'Notrufkasten', 'Uhr', 
    'Thermometer', 'Wetteranzeige', 'Stoppschild',
    'Eisenbahnübergang', 'Gleise', 'Zug', 'Fahrradständer', 
    'Ladestation E-Auto', 'Sonnenbrille', 'Sonnenhut', 'Eisverkauf', 
    'Hotdog-Stand', 'Wurststand', 'Biergarten', 'Straßenfest', 
    'Luftballon', 'Papierkorb', 'Glascontainer', 'Parkschild', 
    'Spielplatz', 'Rutsche', 'Sandkasten', 'Klettergerüst', 'Ampel', 
    'Einbahnstraßenschild', 'Parken-verboten Schild', 'Höchstgeschwindigkeit 30', 
    'Verbot für LKW', 'Spielstrassenschild', 'Schulbus', 'Richtungspfeil', 
    '30 km/h Zone', 'Tempo 50', 'Ausfahrt',
    'Baustelle voraus', 'Vorfahrtsschild', 'Zebrastreifen', 
    'Fußgängerzone', 'Müllcontainer', 'Straßenlaterne', 'Unbegrenzt Schild',
    'Pool', 'Rotes Auto', 'Gelbes Auto', 'Grünes Auto', 'Blaues Auto', 'Weißes Auto', 'Schwarzes Auto',
    'Silbernes Auto', 'Oranges Auto', 'Lila Auto', 'Braunes Auto', 'Pinkes Auto', 'Grau Autos',
    'Traktor', 'Motorrad', 'Roller', 'Bus', 'Wohnwagen', 'Lieferwagen',
    'Straßenbahn', 'U-Bahn Schild', 'S-Bahn Schild', 'Fähre', 'Segelboot', 'Yacht', 'Kanu', 
    'Ruderboot', 'Schlauchboot', 'Dampfer', 'Fischkutter', 
    'Polizeiboot', 'Feuerwehrboot', 'Rettungsboot', 'U-Boot', 'Helikopter', 'Telefonierender Mensch',
    'Winkender Mensch', 'Musiker',

    'Kuh', 'Schaf', 'Dixiklo', 'Bauarbeiter', 'Müllmann', 'Starbucks', 'McDonald\'s', 'Burger King',
    'Porsche', 'Ferrari', 'Landesflagge', 'Cosplay', 'Ruine', 'Sandstrand', 'Bergsee', 'Selfiestick',
    'Flughafen', 'Kreisverkehr', 'Autowerktstatt', 'Motorradfahrer', 'Skateboardfahrer', 'Straßenkünstler',
    'Straßenverkäufer', 'Schuppen', 'Bagger', 'Kran', 'Warnweste', 'Yacht', 'Dreirädriges Fahrzeug',
    'Elefant', 'Stadion', 'Parlament', 'Bibliothek', 'Leuchtturm', 'Windmühle', 'Windrad', 'Fernsehturm',
    'Fitnessstudio', 'Zoo', 'Anhänger', 'Badende Person', 'Surfer', 'Gondelbahn', 'Riesenrad', 'Karusell',
];