import type { CategoryLanguage } from './i18n/locales';

export const categoriesEn = [
    'Car',
    'Tree',
    'Trash can',
    'Window',
    'Door',
    'Storefront',
    'Bicycle',
    'Bench',
    'Mailbox',
    'Bus stop',
    'Tram',
    'Pedestrian crossing',
    'Parking meter',
    'Cell phone',
    'Dog',
    'Cat',
    'Person',
    'Stroller',
    'Shopping bag',
    'Umbrella',
    'Jacket',
    'Hat',
    'Glasses',
    'Backpack',
    'Suitcase',
    'Cart',
    'Truck',
    'Bus',
    'Police car',
    'Fire engine',
    'Bakery',
    'Supermarket',
    'Pharmacy',
    'Bank building',
    'Restaurant',
    'Cafe',
    'Dentist',
    'Hairdresser',
    'Flower shop',
    'Bookstore',
    'Movie theater',
    'Theater',
    'Hotel',
    'Car dealership',
    'Gas station',
    'Car wash',
    'School',
    'Kindergarten',
    'Church',
    'Mosque',
    'Garden',
    'Fence',
    'Gate',
    'Chair',
    'Table',
    'Flower pot',
    'Flag',
    'Poster',
    'Graffiti',
    'Cell phone store',
    'Boutique',
    'Shoe store',
    'Sports shop',
    'Drugstore',
    'Post office',
    'Telephone booth',
    'Gumball machine',
    'Newsstand',
    'Street musician',
    'Jogger',
    'Cyclist',
    'Skater',
    'Wheelchair',
    'Luggage cart',
    'Toolbox',
    'Ladder',
    'Construction site',
    'Crane',
    'Scaffolding',
    'Traffic cone',
    'Caution tape',
    'Shovel',
    'Bucket',
    'Street broom',
    'Street sweeper',
    'Leaf',
    'Stone',
    'Puddle',
    'Water tap',
    'Fire extinguisher',
    'Emergency call box',
    'Clock',
    'Thermometer',
    'Weather display',
    'Stop sign',
    'Bridge',
    'Tunnel',
    'Railroad crossing',
    'Train tracks',
    'Train',
    'Street map',
    'Bike rack',
    'EV charging station',
    'Sunglasses',
    'Sun hat',
    'Ice cream stand',
    'Hot dog stand',
    'Sausage stand',
    'Beer garden',
    'Street festival',
    'Balloon',
    'Trash bin',
    'Glass container',
    'Paper recycling',
    'Parking sign',
    'Playground',
    'Swing',
    'Slide',
    'Sandbox',
    'Jungle gym',
    'Traffic light',
    'One-way street sign',
    'No-parking sign',
    'Speed limit 30 sign',
    'No-trucks sign',
    'Children sign',
    'School bus',
    'Directional arrow',
    '30 km/h zone sign',
    'Speed limit 50 sign',
    'Paid parking zone',
    'No-stopping sign',
    'Merge sign',
    'Exit sign',
    'Right turn sign',
    'Construction ahead sign',
    'Right of way sign',
    'Zebra crossing',
    'Bike lane',
    'Pedestrian zone',
    'Dumpster',
    'Street lamp',
    'Unlimited sign',
    'Pool',
    'Red car',
    'Yellow car',
    'Green car',
    'Blue car',
    'White car',
    'Black car',
    'Silver car',
    'Orange car',
    'Purple car',
    'Brown car',
    'Pink car',
    'Gray cars',
    'Tractor',
    'Motorcycle',
    'Scooter',
    'Bus',
    'RV',
    'Camper van',
    'Delivery van',
    'Tram',
    'Subway sign',
    'Train station sign',
    'Ferry',
    'Sailboat',
    'Yacht',
    'Canoe',
    'Kayak',
    'Inflatable boat',
    'Steamboat',
    'Fishing boat',
    'Police boat',
    'Fire boat',
    'Rescue boat',
    'Submarine',
    'Helicopter',
    'Person on phone',
    'Waving person',
    'Musician',
    'Artist',
];

export const categoriesDe = [
    'Mülltonne',
    'Bankgeschäft',
    'Briefkasten',
    'Bushaltestelle',
    'Straßenbahn',
    'Fußgängerüberweg',
    'Parkuhr',
    'Hund',
    'Katze',
    'Mensch',
    'Kinderwagen',
    'Einkaufstasche',
    'Regenschirm',
    'Jacke',
    'Hut',
    'Rucksack',
    'Koffer',
    'LKW',
    'Bus',
    'Polizeiauto',
    'Feuerwehr',
    'Bäckerei',
    'Supermarkt',
    'Apotheke',
    'Bankgebäude',
    'Restaurant',
    'Café',
    'Zahnarzt',
    'Friseur',
    'Blumenladen',
    'Buchhandlung',
    'Kino',
    'Theater',
    'Hotel',
    'Autohaus',
    'Tankstelle',
    'Waschstraße',
    'Schule',
    'Kindergarten',
    'Kirche',
    'Moschee',
    'Garten',
    'Zaun',
    'Tor',
    'Stuhl',
    'Tisch',
    'Blumentopf',
    'Flagge',
    'Graffiti',
    'Handy-Laden',
    'Schuhgeschäft',
    'Sportgeschäft',
    'Drogerie',
    'Post',
    'Telefonzelle',
    'Kaugummiautomat',
    'Zeitungskiosk',
    'Straßenmusiker',
    'Jogger',
    'Skater',
    'Rollstuhl',
    'Leiter',
    'Baustelle',
    'Gerüst',
    'Verkehrskegel',
    'Absperrband',
    'Schaufel',
    'Eimer',
    'Blatt',
    'Pfütze',
    'Wasserhahn',
    'Feuerlöscher',
    'Notrufkasten',
    'Uhr',
    'Thermometer',
    'Wetteranzeige',
    'Stoppschild',
    'Eisenbahnübergang',
    'Gleise',
    'Zug',
    'Fahrradständer',
    'Ladestation E-Auto',
    'Sonnenbrille',
    'Sonnenhut',
    'Eisverkauf',
    'Hotdog-Stand',
    'Wurststand',
    'Biergarten',
    'Straßenfest',
    'Luftballon',
    'Papierkorb',
    'Glascontainer',
    'Parkschild',
    'Spielplatz',
    'Rutsche',
    'Sandkasten',
    'Klettergerüst',
    'Ampel',
    'Einbahnstraßenschild',
    'Parken-verboten Schild',
    'Höchstgeschwindigkeit 30',
    'Verbot für LKW',
    'Spielstrassenschild',
    'Schulbus',
    'Richtungspfeil',
    '30 km/h Zone',
    'Tempo 50',
    'Ausfahrt',
    'Baustelle voraus',
    'Vorfahrtsschild',
    'Zebrastreifen',
    'Fußgängerzone',
    'Müllcontainer',
    'Straßenlaterne',
    'Unbegrenzt Schild',
    'Pool',
    'Rotes Auto',
    'Gelbes Auto',
    'Grünes Auto',
    'Blaues Auto',
    'Weißes Auto',
    'Schwarzes Auto',
    'Silbernes Auto',
    'Oranges Auto',
    'Lila Auto',
    'Braunes Auto',
    'Pinkes Auto',
    'Grau Autos',
    'Traktor',
    'Motorrad',
    'Roller',
    'Bus',
    'Wohnwagen',
    'Lieferwagen',
    'Straßenbahn',
    'U-Bahn Schild',
    'S-Bahn Schild',
    'Fähre',
    'Segelboot',
    'Yacht',
    'Kanu',
    'Ruderboot',
    'Schlauchboot',
    'Dampfer',
    'Fischkutter',
    'Polizeiboot',
    'Feuerwehrboot',
    'Rettungsboot',
    'U-Boot',
    'Helikopter',
    'Telefonierender Mensch',
    'Winkender Mensch',
    'Musiker',

    'Kuh',
    'Schaf',
    'Dixiklo',
    'Bauarbeiter',
    'Müllmann',
    'Starbucks',
    "McDonald's",
    'Burger King',
    'Porsche',
    'Ferrari',
    'Landesflagge',
    'Cosplay',
    'Ruine',
    'Sandstrand',
    'Bergsee',
    'Selfiestick',
    'Flughafen',
    'Kreisverkehr',
    'Autowerktstatt',
    'Motorradfahrer',
    'Skateboardfahrer',
    'Straßenkünstler',
    'Straßenverkäufer',
    'Schuppen',
    'Bagger',
    'Kran',
    'Warnweste',
    'Yacht',
    'Dreirädriges Fahrzeug',
    'Elefant',
    'Stadion',
    'Parlament',
    'Bibliothek',
    'Leuchtturm',
    'Windmühle',
    'Windrad',
    'Fernsehturm',
    'Fitnessstudio',
    'Zoo',
    'Anhänger',
    'Badende Person',
    'Surfer',
    'Gondelbahn',
    'Riesenrad',
    'Karusell',
];

export const categoriesSimpleDe = [
    'Auto',
    'Baum',
    'Haus',
    'Straße',
    'Schild',
    'Himmel',
    'Wolke',
    'Gras',
    'Fenster',
    'Tür',
    'Schatten',
    'Mensch',
    'Fahrrad',
    'Laterne',
    'Zaun',
    'Busch',
    'Mauer',
    'Dach',
    'Stein',
    'Wasser',
    'Bank',
    'Ampel',
    'Kreuzung',
    'Parkplatz',
    'Mülleimer',
    'LKW',
    'Bus',
    'Motorrad',
    'Hund',
    'Katze',
    'Vogel',
    'Blume',
    'Brücke',
    'Briefkasten',
    'Gullydeckel',
    'Schaufenster',
    'Balkon',
    'Treppe',
    'Kamin',
    'Satellitenschüssel',
    'Plakat',
    'Haltestelle',
    'Bürgersteig',
    'Zebrastreifen',
    'Strommast',
    'Gleise',
    'Graffiti',
    'Hydrant',
    'Weißes Auto',
    'Schwarzes Auto',
    'Rotes Auto',
    'Silbernes Auto',
    'Verkehrsinsel',
    'Wiese',
    'Wald',
    'Feld',
    'Berg',
    'Sand',
];

export const categoriesSimpleEn = [
    'Car',
    'Tree',
    'House',
    'Road',
    'Sign',
    'Sky',
    'Cloud',
    'Grass',
    'Window',
    'Door',
    'Shadow',
    'Person',
    'Bicycle',
    'Street lamp',
    'Fence',
    'Bush',
    'Wall',
    'Roof',
    'Stone',
    'Water',
    'Bench',
    'Traffic light',
    'Intersection',
    'Parking lot',
    'Trash can',
    'Truck',
    'Bus',
    'Motorcycle',
    'Dog',
    'Cat',
    'Bird',
    'Flower',
    'Bridge',
    'Mailbox',
    'Manhole cover',
    'Storefront',
    'Balcony',
    'Stairs',
    'Chimney',
    'Satellite dish',
    'Billboard',
    'Bus stop',
    'Sidewalk',
    'Crosswalk',
    'Utility pole',
    'Railway track',
    'Graffiti',
    'Fire hydrant',
    'White car',
    'Black car',
    'Red car',
    'Silver car',
    'Traffic island',
    'Meadow',
    'Forest',
    'Field',
    'Mountain',
    'Sand',
];

export const categoriesHardDe = [
    'Storchennest',
    'Reetdach',
    'Pferdekutsche',
    'Solarpark',
    'Wasserturm',
    'Schrottplatz',
    'Leuchtturm',
    'Windmühle',
    'Fachwerkhaus',
    'Obelisk',
    'Kreisverkehr mit Kunstwerk',
    'Oberleitung für Busse',
    'Müllwagen',
    'Betonmischer',
    'Botschaftsgebäude',
    'Gewächshaus-Anlage',
    'Weinreben',
    'Olivenbaum',
    'Kaktus',
    'Palmenallee',
    'Bananenstaude',
    'Schneepflug',
    'Seilbahn',
    'Skilift',
    'Hubschrauberlandeplatz',
    'Observatorium',
    'Burgruine',
    'Aquädukt',
    'Wasserfall',
    'Geysir',
    'Hängebrücke',
    'Geschlossene Schranke',
    'Mautstation',
    'Grenzübergang',
    'Militärfahrzeug',
    'Reiterstandbild (Pferd)',
    'Sonnenuhr',
    'Wetterstation',
    'Rot-weißer Funkmast',
    'Blitzer (Radarfalle)',
    'Straßenschild (3+ Sprachen)',
    'Unbefestigte Straße (Dirt Road)',
    'Riesiges Schlagloch',
    'Überflutete Straße',
    'Regenbogen',
    'Heißluftballon',
    'Gedenkkreuz am Straßenrand',
    'Telefonzelle (außer Betrieb)',
    'Traktor mit Anhänger',
    'Golfplatz',
    'Friedhof',
    'Satellitenschüssel auf dem Boden',
    'Glockenturm',
    'Schneemann',
    'Oldtimer',
    'Wohnmobil mit Fahrrädern hinten',
    'Verlassenes Gebäude',
];

export const categoriesHardEn = [
    'Stork nest',
    'Thatch roof',
    'Horse-drawn carriage',
    'Solar farm',
    'Water tower',
    'Junkyard',
    'Lighthouse',
    'Windmill',
    'Half-timbered house',
    'Obelisk',
    'Roundabout with art',
    'Trolleybus lines',
    'Garbage truck',
    'Cement mixer',
    'Embassy building',
    'Greenhouse complex',
    'Vineyards',
    'Olive tree',
    'Cactus',
    'Palm tree avenue',
    'Banana plant',
    'Snowplow',
    'Cable car',
    'Ski lift',
    'Helipad',
    'Observatory',
    'Castle ruins',
    'Aqueduct',
    'Waterfall',
    'Geyser',
    'Suspension bridge',
    'Closed boom barrier',
    'Toll booth',
    'Border crossing',
    'Military vehicle',
    'Equestrian statue (Horse)',
    'Sundial',
    'Weather station',
    'Red and white radio mast',
    'Speed camera',
    'Street sign (3+ languages)',
    'Dirt road',
    'Massive pothole',
    'Flooded road',
    'Rainbow',
    'Hot air balloon',
    'Roadside memorial cross',
    'Out of order phone booth',
    'Tractor with trailer',
    'Golf course',
    'Cemetery',
    'Ground-mounted satellite dish',
    'Bell tower',
    'Snowman',
    'Classic / Vintage car',
    'RV with bikes on back',
    'Abandoned building',
];

// ============================ SPANISH ============================
export const categoriesEs = [
    'Coche',
    'Árbol',
    'Papelera',
    'Ventana',
    'Puerta',
    'Escaparate',
    'Bicicleta',
    'Banco',
    'Buzón',
    'Parada de autobús',
    'Tranvía',
    'Paso de peatones',
    'Parquímetro',
    'Teléfono móvil',
    'Perro',
    'Gato',
    'Persona',
    'Cochecito',
    'Bolsa de la compra',
    'Paraguas',
    'Chaqueta',
    'Sombrero',
    'Gafas',
    'Mochila',
    'Maleta',
    'Carrito',
    'Camión',
    'Autobús',
    'Coche de policía',
    'Camión de bomberos',
    'Panadería',
    'Supermercado',
    'Farmacia',
    'Edificio de banco',
    'Restaurante',
    'Cafetería',
    'Dentista',
    'Peluquería',
    'Floristería',
    'Librería',
    'Cine',
    'Teatro',
    'Hotel',
    'Concesionario',
    'Gasolinera',
    'Túnel de lavado',
    'Escuela',
    'Guardería',
    'Iglesia',
    'Mezquita',
    'Jardín',
    'Valla',
    'Portón',
    'Silla',
    'Mesa',
    'Maceta',
    'Bandera',
    'Cartel',
    'Grafiti',
    'Tienda de móviles',
    'Boutique',
    'Zapatería',
    'Tienda de deportes',
    'Droguería',
    'Oficina de correos',
    'Cabina telefónica',
    'Máquina de chicles',
    'Quiosco',
    'Músico callejero',
    'Corredor',
    'Ciclista',
    'Patinador',
    'Silla de ruedas',
    'Carrito de equipaje',
    'Caja de herramientas',
    'Escalera',
    'Obra',
    'Grúa',
    'Andamio',
    'Cono de tráfico',
    'Cinta de precaución',
    'Pala',
    'Cubo',
    'Escoba de calle',
    'Barredora',
    'Hoja',
    'Piedra',
    'Charco',
    'Grifo',
    'Extintor',
    'Poste de emergencia',
    'Reloj',
    'Termómetro',
    'Panel del tiempo',
    'Señal de stop',
    'Puente',
    'Túnel',
    'Paso a nivel',
    'Vías de tren',
    'Tren',
    'Plano callejero',
    'Aparcabicis',
    'Punto de carga eléctrica',
    'Gafas de sol',
    'Sombrero de sol',
    'Heladería',
    'Puesto de perritos calientes',
    'Puesto de salchichas',
    'Cervecería al aire libre',
    'Fiesta callejera',
    'Globo',
    'Cubo de basura',
    'Contenedor de vidrio',
    'Reciclaje de papel',
    'Señal de aparcamiento',
    'Parque infantil',
    'Columpio',
    'Tobogán',
    'Arenero',
    'Estructura para trepar',
    'Semáforo',
    'Señal de sentido único',
    'Señal de prohibido aparcar',
    'Señal de límite 30',
    'Señal de prohibido camiones',
    'Señal de niños',
    'Autobús escolar',
    'Flecha direccional',
    'Señal de zona 30 km/h',
    'Señal de límite 50',
    'Zona de pago',
    'Señal de prohibido parar',
    'Señal de incorporación',
    'Señal de salida',
    'Señal de giro a la derecha',
    'Señal de obras',
    'Señal de prioridad',
    'Paso de cebra',
    'Carril bici',
    'Zona peatonal',
    'Contenedor de obra',
    'Farola',
    'Señal de fin de límite',
    'Piscina',
    'Coche rojo',
    'Coche amarillo',
    'Coche verde',
    'Coche azul',
    'Coche blanco',
    'Coche negro',
    'Coche plateado',
    'Coche naranja',
    'Coche morado',
    'Coche marrón',
    'Coche rosa',
    'Coches grises',
    'Tractor',
    'Motocicleta',
    'Patinete',
    'Autobús',
    'Autocaravana',
    'Caravana',
    'Furgoneta de reparto',
    'Tranvía',
    'Señal de metro',
    'Señal de estación de tren',
    'Ferry',
    'Velero',
    'Yate',
    'Canoa',
    'Kayak',
    'Bote inflable',
    'Barco de vapor',
    'Barco de pesca',
    'Lancha policial',
    'Barco de bomberos',
    'Bote de rescate',
    'Submarino',
    'Helicóptero',
    'Persona al teléfono',
    'Persona saludando',
    'Músico',
    'Artista',
];

export const categoriesSimpleEs = [
    'Coche',
    'Árbol',
    'Casa',
    'Carretera',
    'Señal',
    'Cielo',
    'Nube',
    'Hierba',
    'Ventana',
    'Puerta',
    'Sombra',
    'Persona',
    'Bicicleta',
    'Farola',
    'Valla',
    'Arbusto',
    'Muro',
    'Tejado',
    'Piedra',
    'Agua',
    'Banco',
    'Semáforo',
    'Cruce',
    'Aparcamiento',
    'Papelera',
    'Camión',
    'Autobús',
    'Motocicleta',
    'Perro',
    'Gato',
    'Pájaro',
    'Flor',
    'Puente',
    'Buzón',
    'Tapa de alcantarilla',
    'Escaparate',
    'Balcón',
    'Escaleras',
    'Chimenea',
    'Antena parabólica',
    'Valla publicitaria',
    'Parada de autobús',
    'Acera',
    'Paso de peatones',
    'Poste eléctrico',
    'Vía de tren',
    'Grafiti',
    'Hidrante',
    'Coche blanco',
    'Coche negro',
    'Coche rojo',
    'Coche plateado',
    'Isleta de tráfico',
    'Prado',
    'Bosque',
    'Campo',
    'Montaña',
    'Arena',
];

export const categoriesHardEs = [
    'Nido de cigüeña',
    'Tejado de paja',
    'Carruaje de caballos',
    'Planta solar',
    'Torre de agua',
    'Desguace',
    'Faro',
    'Molino de viento',
    'Casa de entramado de madera',
    'Obelisco',
    'Rotonda con escultura',
    'Catenarias de trolebús',
    'Camión de basura',
    'Hormigonera',
    'Edificio de embajada',
    'Complejo de invernaderos',
    'Viñedos',
    'Olivo',
    'Cactus',
    'Avenida de palmeras',
    'Platanera',
    'Quitanieves',
    'Teleférico',
    'Telesilla',
    'Helipuerto',
    'Observatorio',
    'Ruinas de castillo',
    'Acueducto',
    'Cascada',
    'Géiser',
    'Puente colgante',
    'Barrera cerrada',
    'Peaje',
    'Paso fronterizo',
    'Vehículo militar',
    'Estatua ecuestre',
    'Reloj de sol',
    'Estación meteorológica',
    'Antena de radio roja y blanca',
    'Radar de velocidad',
    'Señal de calle (3+ idiomas)',
    'Camino de tierra',
    'Bache enorme',
    'Carretera inundada',
    'Arcoíris',
    'Globo aerostático',
    'Cruz conmemorativa',
    'Cabina telefónica fuera de servicio',
    'Tractor con remolque',
    'Campo de golf',
    'Cementerio',
    'Antena parabólica en el suelo',
    'Campanario',
    'Muñeco de nieve',
    'Coche clásico',
    'Autocaravana con bicis detrás',
    'Edificio abandonado',
];

// ============================ FRENCH ============================
export const categoriesFr = [
    'Voiture',
    'Arbre',
    'Poubelle',
    'Fenêtre',
    'Porte',
    'Devanture',
    'Vélo',
    'Banc',
    'Boîte aux lettres',
    'Arrêt de bus',
    'Tramway',
    'Passage piéton',
    'Parcmètre',
    'Téléphone portable',
    'Chien',
    'Chat',
    'Personne',
    'Poussette',
    'Sac de courses',
    'Parapluie',
    'Veste',
    'Chapeau',
    'Lunettes',
    'Sac à dos',
    'Valise',
    'Chariot',
    'Camion',
    'Bus',
    'Voiture de police',
    'Camion de pompiers',
    'Boulangerie',
    'Supermarché',
    'Pharmacie',
    'Banque',
    'Restaurant',
    'Café',
    'Dentiste',
    'Coiffeur',
    'Fleuriste',
    'Librairie',
    'Cinéma',
    'Théâtre',
    'Hôtel',
    'Concessionnaire auto',
    'Station-service',
    'Lavage auto',
    'École',
    "Jardin d'enfants",
    'Église',
    'Mosquée',
    'Jardin',
    'Clôture',
    'Portail',
    'Chaise',
    'Table',
    'Pot de fleurs',
    'Drapeau',
    'Affiche',
    'Graffiti',
    'Magasin de téléphonie',
    'Boutique',
    'Magasin de chaussures',
    'Magasin de sport',
    'Droguerie',
    'Bureau de poste',
    'Cabine téléphonique',
    'Distributeur de chewing-gums',
    'Kiosque à journaux',
    'Musicien de rue',
    'Joggeur',
    'Cycliste',
    'Patineur',
    'Fauteuil roulant',
    'Chariot à bagages',
    'Boîte à outils',
    'Échelle',
    'Chantier',
    'Grue',
    'Échafaudage',
    'Cône de signalisation',
    'Ruban de signalisation',
    'Pelle',
    'Seau',
    'Balai de rue',
    'Balayeuse',
    'Feuille',
    'Pierre',
    'Flaque',
    'Robinet',
    'Extincteur',
    "Borne d'appel d'urgence",
    'Horloge',
    'Thermomètre',
    'Afficheur météo',
    'Panneau stop',
    'Pont',
    'Tunnel',
    'Passage à niveau',
    'Voies ferrées',
    'Train',
    'Plan de ville',
    'Range-vélos',
    'Borne de recharge',
    'Lunettes de soleil',
    'Chapeau de soleil',
    'Stand de glaces',
    'Stand de hot-dogs',
    'Stand de saucisses',
    'Brasserie en plein air',
    'Fête de rue',
    'Ballon',
    'Corbeille à déchets',
    'Conteneur à verre',
    'Recyclage du papier',
    'Panneau de stationnement',
    'Aire de jeux',
    'Balançoire',
    'Toboggan',
    'Bac à sable',
    'Cage à grimper',
    'Feu de circulation',
    'Panneau sens unique',
    'Panneau stationnement interdit',
    'Panneau limite 30',
    'Panneau interdit aux camions',
    'Panneau enfants',
    'Bus scolaire',
    'Flèche directionnelle',
    'Panneau zone 30 km/h',
    'Panneau limite 50',
    'Zone de stationnement payant',
    'Panneau arrêt interdit',
    "Panneau d'insertion",
    'Panneau de sortie',
    'Panneau tourner à droite',
    'Panneau travaux',
    'Panneau priorité',
    'Passage piéton',
    'Piste cyclable',
    'Zone piétonne',
    'Benne à ordures',
    'Lampadaire',
    'Panneau fin de limitation',
    'Piscine',
    'Voiture rouge',
    'Voiture jaune',
    'Voiture verte',
    'Voiture bleue',
    'Voiture blanche',
    'Voiture noire',
    'Voiture grise argentée',
    'Voiture orange',
    'Voiture violette',
    'Voiture marron',
    'Voiture rose',
    'Voitures grises',
    'Tracteur',
    'Moto',
    'Trottinette',
    'Bus',
    'Camping-car',
    'Van aménagé',
    'Camionnette de livraison',
    'Tramway',
    'Panneau de métro',
    'Panneau de gare',
    'Ferry',
    'Voilier',
    'Yacht',
    'Canoë',
    'Kayak',
    'Bateau gonflable',
    'Bateau à vapeur',
    'Bateau de pêche',
    'Bateau de police',
    'Bateau-pompe',
    'Canot de sauvetage',
    'Sous-marin',
    'Hélicoptère',
    'Personne au téléphone',
    'Personne qui salue',
    'Musicien',
    'Artiste',
];

export const categoriesSimpleFr = [
    'Voiture',
    'Arbre',
    'Maison',
    'Route',
    'Panneau',
    'Ciel',
    'Nuage',
    'Herbe',
    'Fenêtre',
    'Porte',
    'Ombre',
    'Personne',
    'Vélo',
    'Lampadaire',
    'Clôture',
    'Buisson',
    'Mur',
    'Toit',
    'Pierre',
    'Eau',
    'Banc',
    'Feu de circulation',
    'Intersection',
    'Parking',
    'Poubelle',
    'Camion',
    'Bus',
    'Moto',
    'Chien',
    'Chat',
    'Oiseau',
    'Fleur',
    'Pont',
    'Boîte aux lettres',
    "Plaque d'égout",
    'Devanture',
    'Balcon',
    'Escalier',
    'Cheminée',
    'Antenne parabolique',
    'Panneau publicitaire',
    'Arrêt de bus',
    'Trottoir',
    'Passage piéton',
    'Poteau électrique',
    'Voie ferrée',
    'Graffiti',
    "Bouche d'incendie",
    'Voiture blanche',
    'Voiture noire',
    'Voiture rouge',
    'Voiture grise argentée',
    'Îlot directionnel',
    'Prairie',
    'Forêt',
    'Champ',
    'Montagne',
    'Sable',
];

export const categoriesHardFr = [
    'Nid de cigogne',
    'Toit de chaume',
    'Calèche',
    'Ferme solaire',
    "Château d'eau",
    'Casse automobile',
    'Phare',
    'Moulin à vent',
    'Maison à colombages',
    'Obélisque',
    "Rond-point avec œuvre d'art",
    'Lignes de trolleybus',
    'Camion poubelle',
    'Bétonnière',
    "Bâtiment d'ambassade",
    'Complexe de serres',
    'Vignobles',
    'Olivier',
    'Cactus',
    'Allée de palmiers',
    'Bananier',
    'Chasse-neige',
    'Téléphérique',
    'Télésiège',
    'Hélisurface',
    'Observatoire',
    'Ruines de château',
    'Aqueduc',
    'Cascade',
    'Geyser',
    'Pont suspendu',
    'Barrière fermée',
    'Poste de péage',
    'Poste-frontière',
    'Véhicule militaire',
    'Statue équestre',
    'Cadran solaire',
    'Station météo',
    'Antenne radio rouge et blanche',
    'Radar automatique',
    'Panneau de rue (3+ langues)',
    'Chemin de terre',
    'Énorme nid-de-poule',
    'Route inondée',
    'Arc-en-ciel',
    'Montgolfière',
    'Croix commémorative',
    'Cabine téléphonique hors service',
    'Tracteur avec remorque',
    'Terrain de golf',
    'Cimetière',
    'Antenne parabolique au sol',
    'Clocher',
    'Bonhomme de neige',
    'Voiture de collection',
    "Camping-car avec vélos à l'arrière",
    'Bâtiment abandonné',
];

// ============================ CHINESE ============================
export const categoriesZh = [
    '汽车',
    '树',
    '垃圾桶',
    '窗户',
    '门',
    '店面',
    '自行车',
    '长椅',
    '邮筒',
    '公交站',
    '有轨电车',
    '人行横道',
    '停车计时器',
    '手机',
    '狗',
    '猫',
    '人',
    '婴儿车',
    '购物袋',
    '雨伞',
    '夹克',
    '帽子',
    '眼镜',
    '背包',
    '行李箱',
    '手推车',
    '卡车',
    '公交车',
    '警车',
    '消防车',
    '面包店',
    '超市',
    '药店',
    '银行大楼',
    '餐厅',
    '咖啡馆',
    '牙医',
    '理发店',
    '花店',
    '书店',
    '电影院',
    '剧院',
    '酒店',
    '汽车经销店',
    '加油站',
    '洗车场',
    '学校',
    '幼儿园',
    '教堂',
    '清真寺',
    '花园',
    '栅栏',
    '大门',
    '椅子',
    '桌子',
    '花盆',
    '旗帜',
    '海报',
    '涂鸦',
    '手机店',
    '精品店',
    '鞋店',
    '体育用品店',
    '日用品店',
    '邮局',
    '电话亭',
    '口香糖机',
    '报刊亭',
    '街头音乐家',
    '慢跑者',
    '骑行者',
    '滑板者',
    '轮椅',
    '行李车',
    '工具箱',
    '梯子',
    '工地',
    '起重机',
    '脚手架',
    '交通锥',
    '警示带',
    '铁锹',
    '水桶',
    '街道扫帚',
    '扫地车',
    '树叶',
    '石头',
    '水坑',
    '水龙头',
    '灭火器',
    '紧急呼叫箱',
    '时钟',
    '温度计',
    '天气显示屏',
    '停车标志',
    '桥',
    '隧道',
    '铁道路口',
    '铁轨',
    '火车',
    '街区地图',
    '自行车架',
    '电动车充电站',
    '太阳镜',
    '遮阳帽',
    '冰淇淋摊',
    '热狗摊',
    '香肠摊',
    '啤酒花园',
    '街头节庆',
    '气球',
    '垃圾箱',
    '玻璃回收箱',
    '纸张回收',
    '停车标牌',
    '游乐场',
    '秋千',
    '滑梯',
    '沙坑',
    '攀爬架',
    '红绿灯',
    '单行道标志',
    '禁止停车标志',
    '限速30标志',
    '禁止卡车标志',
    '儿童标志',
    '校车',
    '方向箭头',
    '30公里限速区标志',
    '限速50标志',
    '收费停车区',
    '禁止停留标志',
    '合流标志',
    '出口标志',
    '右转标志',
    '前方施工标志',
    '优先通行标志',
    '斑马线',
    '自行车道',
    '步行区',
    '大型垃圾箱',
    '路灯',
    '解除限速标志',
    '泳池',
    '红色汽车',
    '黄色汽车',
    '绿色汽车',
    '蓝色汽车',
    '白色汽车',
    '黑色汽车',
    '银色汽车',
    '橙色汽车',
    '紫色汽车',
    '棕色汽车',
    '粉色汽车',
    '灰色汽车',
    '拖拉机',
    '摩托车',
    '踏板车',
    '公交车',
    '房车',
    '露营车',
    '送货车',
    '有轨电车',
    '地铁标志',
    '火车站标志',
    '渡轮',
    '帆船',
    '游艇',
    '独木舟',
    '皮划艇',
    '充气艇',
    '蒸汽船',
    '渔船',
    '警用船',
    '消防船',
    '救生艇',
    '潜艇',
    '直升机',
    '打电话的人',
    '挥手的人',
    '音乐家',
    '艺术家',
];

export const categoriesSimpleZh = [
    '汽车',
    '树',
    '房子',
    '道路',
    '标志',
    '天空',
    '云',
    '草',
    '窗户',
    '门',
    '影子',
    '人',
    '自行车',
    '路灯',
    '栅栏',
    '灌木',
    '墙',
    '屋顶',
    '石头',
    '水',
    '长椅',
    '红绿灯',
    '十字路口',
    '停车场',
    '垃圾桶',
    '卡车',
    '公交车',
    '摩托车',
    '狗',
    '猫',
    '鸟',
    '花',
    '桥',
    '邮筒',
    '井盖',
    '店面',
    '阳台',
    '楼梯',
    '烟囱',
    '卫星天线',
    '广告牌',
    '公交站',
    '人行道',
    '人行横道',
    '电线杆',
    '铁轨',
    '涂鸦',
    '消防栓',
    '白色汽车',
    '黑色汽车',
    '红色汽车',
    '银色汽车',
    '交通岛',
    '草地',
    '森林',
    '田地',
    '山',
    '沙',
];

export const categoriesHardZh = [
    '鹳巢',
    '茅草屋顶',
    '马车',
    '太阳能发电场',
    '水塔',
    '废车场',
    '灯塔',
    '风车',
    '半木结构房屋',
    '方尖碑',
    '带艺术品的环岛',
    '无轨电车线',
    '垃圾车',
    '水泥搅拌车',
    '大使馆建筑',
    '温室群',
    '葡萄园',
    '橄榄树',
    '仙人掌',
    '棕榈大道',
    '香蕉树',
    '扫雪车',
    '缆车',
    '滑雪缆椅',
    '直升机停机坪',
    '天文台',
    '城堡遗址',
    '渡槽',
    '瀑布',
    '间歇泉',
    '悬索桥',
    '关闭的栏杆',
    '收费站',
    '边境口岸',
    '军用车辆',
    '骑马雕像',
    '日晷',
    '气象站',
    '红白无线电塔',
    '测速摄像头',
    '路牌（3种以上语言）',
    '土路',
    '巨大坑洞',
    '被淹的道路',
    '彩虹',
    '热气球',
    '路边纪念十字架',
    '停用的电话亭',
    '拖拉机带拖车',
    '高尔夫球场',
    '墓地',
    '落地卫星天线',
    '钟楼',
    '雪人',
    '老爷车',
    '后挂自行车的房车',
    '废弃建筑',
];

// ===================== LOCALE-KEYED MAPS =====================
// Keyed by the game's shared board language. German/English have curated pools;
// Spanish/French/Chinese are translations of the English pool.
export const categoriesBalanced: Record<CategoryLanguage, string[]> = {
    german: categoriesDe,
    english: categoriesEn,
    spanish: categoriesEs,
    french: categoriesFr,
    chinese: categoriesZh,
};

export const categoriesSimple: Record<CategoryLanguage, string[]> = {
    german: categoriesSimpleDe,
    english: categoriesSimpleEn,
    spanish: categoriesSimpleEs,
    french: categoriesSimpleFr,
    chinese: categoriesSimpleZh,
};

export const categoriesHard: Record<CategoryLanguage, string[]> = {
    german: categoriesHardDe,
    english: categoriesHardEn,
    spanish: categoriesHardEs,
    french: categoriesHardFr,
    chinese: categoriesHardZh,
};

// GeoGuessr meta now lives in one canonical, multilingual list.
export { geoGuessrMeta, type GeoMeta } from './geoMeta';
