export const categoriesEn = [
  "Car",
  "Tree",
  "Trash can",
  "Window",
  "Door",
  "Storefront",
  "Bicycle",
  "Bench",
  "Mailbox",
  "Bus stop",
  "Tram",
  "Pedestrian crossing",
  "Parking meter",
  "Cell phone",
  "Dog",
  "Cat",
  "Person",
  "Stroller",
  "Shopping bag",
  "Umbrella",
  "Jacket",
  "Hat",
  "Glasses",
  "Backpack",
  "Suitcase",
  "Cart",
  "Truck",
  "Bus",
  "Police car",
  "Fire engine",
  "Bakery",
  "Supermarket",
  "Pharmacy",
  "Bank building",
  "Restaurant",
  "Cafe",
  "Dentist",
  "Hairdresser",
  "Flower shop",
  "Bookstore",
  "Movie theater",
  "Theater",
  "Hotel",
  "Car dealership",
  "Gas station",
  "Car wash",
  "School",
  "Kindergarten",
  "Church",
  "Mosque",
  "Garden",
  "Fence",
  "Gate",
  "Chair",
  "Table",
  "Flower pot",
  "Flag",
  "Poster",
  "Graffiti",
  "Cell phone store",
  "Boutique",
  "Shoe store",
  "Sports shop",
  "Drugstore",
  "Post office",
  "Telephone booth",
  "Gumball machine",
  "Newsstand",
  "Street musician",
  "Jogger",
  "Cyclist",
  "Skater",
  "Wheelchair",
  "Luggage cart",
  "Toolbox",
  "Ladder",
  "Construction site",
  "Crane",
  "Scaffolding",
  "Traffic cone",
  "Caution tape",
  "Shovel",
  "Bucket",
  "Street broom",
  "Street sweeper",
  "Leaf",
  "Stone",
  "Puddle",
  "Water tap",
  "Fire extinguisher",
  "Emergency call box",
  "Clock",
  "Thermometer",
  "Weather display",
  "Stop sign",
  "Bridge",
  "Tunnel",
  "Railroad crossing",
  "Train tracks",
  "Train",
  "Street map",
  "Bike rack",
  "EV charging station",
  "Sunglasses",
  "Sun hat",
  "Ice cream stand",
  "Hot dog stand",
  "Sausage stand",
  "Beer garden",
  "Street festival",
  "Balloon",
  "Trash bin",
  "Glass container",
  "Paper recycling",
  "Parking sign",
  "Playground",
  "Swing",
  "Slide",
  "Sandbox",
  "Jungle gym",
  "Traffic light",
  "One-way street sign",
  "No-parking sign",
  "Speed limit 30 sign",
  "No-trucks sign",
  "Children sign",
  "School bus",
  "Directional arrow",
  "30 km/h zone sign",
  "Speed limit 50 sign",
  "Paid parking zone",
  "No-stopping sign",
  "Merge sign",
  "Exit sign",
  "Right turn sign",
  "Construction ahead sign",
  "Right of way sign",
  "Zebra crossing",
  "Bike lane",
  "Pedestrian zone",
  "Dumpster",
  "Street lamp",
  "Unlimited sign",
  "Pool",
  "Red car",
  "Yellow car",
  "Green car",
  "Blue car",
  "White car",
  "Black car",
  "Silver car",
  "Orange car",
  "Purple car",
  "Brown car",
  "Pink car",
  "Gray cars",
  "Tractor",
  "Motorcycle",
  "Scooter",
  "Bus",
  "RV",
  "Camper van",
  "Delivery van",
  "Tram",
  "Subway sign",
  "Train station sign",
  "Ferry",
  "Sailboat",
  "Yacht",
  "Canoe",
  "Kayak",
  "Inflatable boat",
  "Steamboat",
  "Fishing boat",
  "Police boat",
  "Fire boat",
  "Rescue boat",
  "Submarine",
  "Helicopter",
  "Person on phone",
  "Waving person",
  "Musician",
  "Artist",
];

export const categoriesDe = [
  "Mülltonne",
  "Bankgeschäft",
  "Briefkasten",
  "Bushaltestelle",
  "Straßenbahn",
  "Fußgängerüberweg",
  "Parkuhr",
  "Hund",
  "Katze",
  "Mensch",
  "Kinderwagen",
  "Einkaufstasche",
  "Regenschirm",
  "Jacke",
  "Hut",
  "Rucksack",
  "Koffer",
  "LKW",
  "Bus",
  "Polizeiauto",
  "Feuerwehr",
  "Bäckerei",
  "Supermarkt",
  "Apotheke",
  "Bankgebäude",
  "Restaurant",
  "Café",
  "Zahnarzt",
  "Friseur",
  "Blumenladen",
  "Buchhandlung",
  "Kino",
  "Theater",
  "Hotel",
  "Autohaus",
  "Tankstelle",
  "Waschstraße",
  "Schule",
  "Kindergarten",
  "Kirche",
  "Moschee",
  "Garten",
  "Zaun",
  "Tor",
  "Stuhl",
  "Tisch",
  "Blumentopf",
  "Flagge",
  "Graffiti",
  "Handy-Laden",
  "Schuhgeschäft",
  "Sportgeschäft",
  "Drogerie",
  "Post",
  "Telefonzelle",
  "Kaugummiautomat",
  "Zeitungskiosk",
  "Straßenmusiker",
  "Jogger",
  "Skater",
  "Rollstuhl",
  "Leiter",
  "Baustelle",
  "Gerüst",
  "Verkehrskegel",
  "Absperrband",
  "Schaufel",
  "Eimer",
  "Blatt",
  "Pfütze",
  "Wasserhahn",
  "Feuerlöscher",
  "Notrufkasten",
  "Uhr",
  "Thermometer",
  "Wetteranzeige",
  "Stoppschild",
  "Eisenbahnübergang",
  "Gleise",
  "Zug",
  "Fahrradständer",
  "Ladestation E-Auto",
  "Sonnenbrille",
  "Sonnenhut",
  "Eisverkauf",
  "Hotdog-Stand",
  "Wurststand",
  "Biergarten",
  "Straßenfest",
  "Luftballon",
  "Papierkorb",
  "Glascontainer",
  "Parkschild",
  "Spielplatz",
  "Rutsche",
  "Sandkasten",
  "Klettergerüst",
  "Ampel",
  "Einbahnstraßenschild",
  "Parken-verboten Schild",
  "Höchstgeschwindigkeit 30",
  "Verbot für LKW",
  "Spielstrassenschild",
  "Schulbus",
  "Richtungspfeil",
  "30 km/h Zone",
  "Tempo 50",
  "Ausfahrt",
  "Baustelle voraus",
  "Vorfahrtsschild",
  "Zebrastreifen",
  "Fußgängerzone",
  "Müllcontainer",
  "Straßenlaterne",
  "Unbegrenzt Schild",
  "Pool",
  "Rotes Auto",
  "Gelbes Auto",
  "Grünes Auto",
  "Blaues Auto",
  "Weißes Auto",
  "Schwarzes Auto",
  "Silbernes Auto",
  "Oranges Auto",
  "Lila Auto",
  "Braunes Auto",
  "Pinkes Auto",
  "Grau Autos",
  "Traktor",
  "Motorrad",
  "Roller",
  "Bus",
  "Wohnwagen",
  "Lieferwagen",
  "Straßenbahn",
  "U-Bahn Schild",
  "S-Bahn Schild",
  "Fähre",
  "Segelboot",
  "Yacht",
  "Kanu",
  "Ruderboot",
  "Schlauchboot",
  "Dampfer",
  "Fischkutter",
  "Polizeiboot",
  "Feuerwehrboot",
  "Rettungsboot",
  "U-Boot",
  "Helikopter",
  "Telefonierender Mensch",
  "Winkender Mensch",
  "Musiker",

  "Kuh",
  "Schaf",
  "Dixiklo",
  "Bauarbeiter",
  "Müllmann",
  "Starbucks",
  "McDonald's",
  "Burger King",
  "Porsche",
  "Ferrari",
  "Landesflagge",
  "Cosplay",
  "Ruine",
  "Sandstrand",
  "Bergsee",
  "Selfiestick",
  "Flughafen",
  "Kreisverkehr",
  "Autowerktstatt",
  "Motorradfahrer",
  "Skateboardfahrer",
  "Straßenkünstler",
  "Straßenverkäufer",
  "Schuppen",
  "Bagger",
  "Kran",
  "Warnweste",
  "Yacht",
  "Dreirädriges Fahrzeug",
  "Elefant",
  "Stadion",
  "Parlament",
  "Bibliothek",
  "Leuchtturm",
  "Windmühle",
  "Windrad",
  "Fernsehturm",
  "Fitnessstudio",
  "Zoo",
  "Anhänger",
  "Badende Person",
  "Surfer",
  "Gondelbahn",
  "Riesenrad",
  "Karusell",
];

export const categoriesSimpleDe = [
  "Auto",
  "Baum",
  "Haus",
  "Straße",
  "Schild",
  "Himmel",
  "Wolke",
  "Gras",
  "Fenster",
  "Tür",
  "Schatten",
  "Mensch",
  "Fahrrad",
  "Laterne",
  "Zaun",
  "Busch",
  "Mauer",
  "Dach",
  "Stein",
  "Wasser",
  "Bank",
  "Ampel",
  "Kreuzung",
  "Parkplatz",
  "Mülleimer",
  "LKW",
  "Bus",
  "Motorrad",
  "Hund",
  "Katze",
  "Vogel",
  "Blume",
  "Brücke",
  "Briefkasten",
  "Gullydeckel",
  "Schaufenster",
  "Balkon",
  "Treppe",
  "Kamin",
  "Satellitenschüssel",
  "Plakat",
  "Haltestelle",
  "Bürgersteig",
  "Zebrastreifen",
  "Strommast",
  "Gleise",
  "Graffiti",
  "Hydrant",
  "Weißes Auto",
  "Schwarzes Auto",
  "Rotes Auto",
  "Silbernes Auto",
  "Verkehrsinsel",
  "Wiese",
  "Wald",
  "Feld",
  "Berg",
  "Sand",
];

export const categoriesSimpleEn = [
  "Car",
  "Tree",
  "House",
  "Road",
  "Sign",
  "Sky",
  "Cloud",
  "Grass",
  "Window",
  "Door",
  "Shadow",
  "Person",
  "Bicycle",
  "Street lamp",
  "Fence",
  "Bush",
  "Wall",
  "Roof",
  "Stone",
  "Water",
  "Bench",
  "Traffic light",
  "Intersection",
  "Parking lot",
  "Trash can",
  "Truck",
  "Bus",
  "Motorcycle",
  "Dog",
  "Cat",
  "Bird",
  "Flower",
  "Bridge",
  "Mailbox",
  "Manhole cover",
  "Storefront",
  "Balcony",
  "Stairs",
  "Chimney",
  "Satellite dish",
  "Billboard",
  "Bus stop",
  "Sidewalk",
  "Crosswalk",
  "Utility pole",
  "Railway track",
  "Graffiti",
  "Fire hydrant",
  "White car",
  "Black car",
  "Red car",
  "Silver car",
  "Traffic island",
  "Meadow",
  "Forest",
  "Field",
  "Mountain",
  "Sand",
];

export const categoriesHardDe = [
  "Storchennest",
  "Reetdach",
  "Pferdekutsche",
  "Solarpark",
  "Wasserturm",
  "Schrottplatz",
  "Leuchtturm",
  "Windmühle",
  "Fachwerkhaus",
  "Obelisk",
  "Kreisverkehr mit Kunstwerk",
  "Oberleitung für Busse",
  "Müllwagen",
  "Betonmischer",
  "Botschaftsgebäude",
  "Gewächshaus-Anlage",
  "Weinreben",
  "Olivenbaum",
  "Kaktus",
  "Palmenallee",
  "Bananenstaude",
  "Schneepflug",
  "Seilbahn",
  "Skilift",
  "Hubschrauberlandeplatz",
  "Observatorium",
  "Burgruine",
  "Aquädukt",
  "Wasserfall",
  "Geysir",
  "Hängebrücke",
  "Geschlossene Schranke",
  "Mautstation",
  "Grenzübergang",
  "Militärfahrzeug",
  "Reiterstandbild (Pferd)",
  "Sonnenuhr",
  "Wetterstation",
  "Rot-weißer Funkmast",
  "Blitzer (Radarfalle)",
  "Straßenschild (3+ Sprachen)",
  "Unbefestigte Straße (Dirt Road)",
  "Riesiges Schlagloch",
  "Überflutete Straße",
  "Regenbogen",
  "Heißluftballon",
  "Gedenkkreuz am Straßenrand",
  "Telefonzelle (außer Betrieb)",
  "Traktor mit Anhänger",
  "Golfplatz",
  "Friedhof",
  "Satellitenschüssel auf dem Boden",
  "Glockenturm",
  "Schneemann",
  "Oldtimer",
  "Wohnmobil mit Fahrrädern hinten",
  "Verlassenes Gebäude",
];

export const categoriesHardEn = [
  "Stork nest",
  "Thatch roof",
  "Horse-drawn carriage",
  "Solar farm",
  "Water tower",
  "Junkyard",
  "Lighthouse",
  "Windmill",
  "Half-timbered house",
  "Obelisk",
  "Roundabout with art",
  "Trolleybus lines",
  "Garbage truck",
  "Cement mixer",
  "Embassy building",
  "Greenhouse complex",
  "Vineyards",
  "Olive tree",
  "Cactus",
  "Palm tree avenue",
  "Banana plant",
  "Snowplow",
  "Cable car",
  "Ski lift",
  "Helipad",
  "Observatory",
  "Castle ruins",
  "Aqueduct",
  "Waterfall",
  "Geyser",
  "Suspension bridge",
  "Closed boom barrier",
  "Toll booth",
  "Border crossing",
  "Military vehicle",
  "Equestrian statue (Horse)",
  "Sundial",
  "Weather station",
  "Red and white radio mast",
  "Speed camera",
  "Street sign (3+ languages)",
  "Dirt road",
  "Massive pothole",
  "Flooded road",
  "Rainbow",
  "Hot air balloon",
  "Roadside memorial cross",
  "Out of order phone booth",
  "Tractor with trailer",
  "Golf course",
  "Cemetery",
  "Ground-mounted satellite dish",
  "Bell tower",
  "Snowman",
  "Classic / Vintage car",
  "RV with bikes on back",
  "Abandoned building",
];

interface GeoMeta {
  term: string;
  countries: string[];
  description: string;
  category:
    | "Vehicle"
    | "Camera"
    | "Infrastructure"
    | "Nature"
    | "Plate"
    | "Marking";
  term_hint: string;
}

export const GeoGuessrMetaDe: GeoMeta[] = [
  // --- VEHICLE ---
  {
    term: "Schwarzer Schnorchel",
    countries: ["Kenia", "Mongolei"],
    description: "Ansaugrohr vorne rechts.",
    category: "Vehicle",
    term_hint: "Ostafrika oder zentralasiatische Steppe",
  },
  {
    term: "Dachträger + Reifen",
    countries: ["Guatemala"],
    description: "Dachträger mit Reserverad.",
    category: "Vehicle",
    term_hint: "Zentralamerika",
  },
  {
    term: "Dünne Dachstangen",
    countries: ["Kirgisistan", "Laos", "Mongolei"],
    description: "Filigrane Gepäckträger.",
    category: "Vehicle",
    term_hint: "Zentral- oder Südostasien",
  },
  {
    term: "Schwarzes Tape (Dach)",
    countries: ["Ghana"],
    description: "Vorne rechts am Träger.",
    category: "Vehicle",
    term_hint: "Westafrika",
  },
  {
    term: "Rotes Tape (Dach)",
    countries: ["Ghana"],
    description: "Seltene Variante hinten am Träger.",
    category: "Vehicle",
    term_hint: "Westafrika",
  },
  {
    term: "Weiße Seitenspiegel",
    countries: ["Nigeria"],
    description: "Spiegel des Google-Autos im Bild.",
    category: "Vehicle",
    term_hint: "Westafrika",
  },
  {
    term: "Schwarze Seitenspiegel",
    countries: ["Argentinien", "Uruguay", "Peru"],
    description: "Spiegel von schwarzen Google-Autos.",
    category: "Vehicle",
    term_hint: "Südamerika",
  },
  {
    term: "Weißer Pickup (Heck)",
    countries: ["Thailand", "Philippinen"],
    description: "Ladekante unten im Bild.",
    category: "Vehicle",
    term_hint: "Südostasien",
  },
  {
    term: "Roll Bars (Heck)",
    countries: ["Senegal", "Nigeria"],
    description: "Metallbügel über der Ladefläche.",
    category: "Vehicle",
    term_hint: "Westafrika",
  },
  {
    term: "Helm-Schatten",
    countries: ["Vietnam"],
    description: "Der Fahrer des Street-View-Motorrads.",
    category: "Vehicle",
    term_hint: "Südostasien",
  },
  {
    term: "Camping-Ausrüstung",
    countries: ["Mongolei"],
    description: "Planen und Zeug auf dem Pickup.",
    category: "Vehicle",
    term_hint: "Zentralasien",
  },
  {
    term: "Kugel-Antenne",
    countries: ["Australien"],
    description: "Funkantenne am Auto.",
    category: "Vehicle",
    term_hint: "Ozeanien",
  },
  {
    term: "Eskorte (Polizei)",
    countries: ["Kenia", "Nigeria", "Tunesien"],
    description: "Fahrzeug fährt voraus oder hinterher.",
    category: "Vehicle",
    term_hint: "Afrika",
  },
  {
    term: "Rotes Google-Auto",
    countries: ["Ukraine"],
    description: "Rote Motorhaube sichtbar.",
    category: "Vehicle",
    term_hint: "Osteuropa",
  },
  {
    term: "Front-Blur (Auto)",
    countries: ["Sri Lanka", "Indonesien"],
    description: "Stark zensierte Motorhaube.",
    category: "Vehicle",
    term_hint: "Süd- oder Südostasien",
  },
  {
    term: "Tuk-Tuk",
    countries: ["Indien", "Bangladesch", "Sri Lanka"],
    description: "Dreirädrige Taxis im Verkehr.",
    category: "Vehicle",
    term_hint: "Südasien",
  },
  {
    term: "Gelbes Taxi",
    countries: ["Kolumbien", "Peru", "New York (USA)"],
    description: "Spezifische Taxifarben.",
    category: "Vehicle",
    term_hint: "Nord- oder Südamerika",
  },

  // --- INFRASTRUCTURE ---
  {
    term: "Leitermast (Beton)",
    countries: ["Polen", "Ungarn", "Rumänien"],
    description: "Typische osteuropäische Strommasten.",
    category: "Infrastructure",
    term_hint: "Osteuropa",
  },
  {
    term: "Holzmast + Metalldach",
    countries: ["Japan"],
    description: "Regenschutz auf Strommasten.",
    category: "Infrastructure",
    term_hint: "Ostasien",
  },
  {
    term: "Pfosten (Roter Ring)",
    countries: ["Frankreich", "Spanien"],
    description: "Klassischer Leitpfosten.",
    category: "Infrastructure",
    term_hint: "Südwesteuropa",
  },
  {
    term: "Pfosten (Gelb. Reflektor)",
    countries: ["Dänemark"],
    description: "Oft mit rotem Strich kombiniert.",
    category: "Infrastructure",
    term_hint: "Nordeuropa / Skandinavien",
  },
  {
    term: "A-Mast (Holz)",
    countries: ["Finnland", "Schweden"],
    description: "Gestützte Strommasten.",
    category: "Infrastructure",
    term_hint: "Skandinavien",
  },
  {
    term: "A-Mast (Beton)",
    countries: ["Brasilien", "Chile"],
    description: "Südamerikanische Stützmasten.",
    category: "Infrastructure",
    term_hint: "Südamerika",
  },
  {
    term: "Hexagon-Mast",
    countries: ["Mexiko", "Kolumbien"],
    description: "Masten mit hexagonalem Querschnitt.",
    category: "Infrastructure",
    term_hint: "Lateinamerika",
  },
  {
    term: "Blaue Schildrückseite",
    countries: ["Frankreich"],
    description: "Rückseite von Wegweisern.",
    category: "Infrastructure",
    term_hint: "Westeuropa",
  },
  {
    term: "Gelbe Schildrückseite",
    countries: ["Griechenland"],
    description: "Rückseite von Ortsschildern.",
    category: "Infrastructure",
    term_hint: "Südeuropa",
  },
  {
    term: "Mastfuß (gestreift)",
    countries: ["Indonesien", "Malaysia", "Pakistan"],
    description: "Bemalte untere Meter.",
    category: "Infrastructure",
    term_hint: "Südost- oder Südasien",
  },
  {
    term: "Warnfarben-Mast",
    countries: ["Taiwan", "Südkorea"],
    description: "Gelb-Schwarz an Masten.",
    category: "Infrastructure",
    term_hint: "Ostasien",
  },
  {
    term: "Großer Wasserturm",
    countries: ["USA"],
    description: "Oft mit dem Namen der Stadt.",
    category: "Infrastructure",
    term_hint: "Nordamerika",
  },
  {
    term: "Beton-Bushaltestelle",
    countries: ["Russland", "Ukraine", "Baltikum"],
    description: "Sowjetische Architektur.",
    category: "Infrastructure",
    term_hint: "Ehemalige Sowjetstaaten",
  },
  {
    term: "Gelber Hydrant",
    countries: ["USA", "Kanada"],
    description: "Typische Straßenhydranten.",
    category: "Infrastructure",
    term_hint: "Nordamerika",
  },
  {
    term: "Rote Backsteinhäuser",
    countries: ["Großbritannien", "Niederlande"],
    description: "Sehr einheitliche Architektur.",
    category: "Infrastructure",
    term_hint: "Nordwesteuropa",
  },
  {
    term: "Pfosten (Schrägstrich)",
    countries: ["Österreich"],
    description: "Leitpfosten mit 2 Punkten.",
    category: "Infrastructure",
    term_hint: "Mitteleuropa (Alpen)",
  },

  // --- MARKING ---
  {
    term: "Gelbe Außenlinie",
    countries: ["Südafrika", "Botswana", "Lesotho", "Eswatini"],
    description: "Fahrbahnbegrenzung.",
    category: "Marking",
    term_hint: "Südliches Afrika",
  },
  {
    term: "Doppelte gelbe Mitte",
    countries: ["USA", "Kanada", "Mexiko", "Brasilien"],
    description: "Trennt den Gegenverkehr.",
    category: "Marking",
    term_hint: "Nord- oder Südamerika",
  },
  {
    term: "Einfache gelbe Mitte",
    countries: ["Norwegen"],
    description: "Skandinavische Ausnahme.",
    category: "Marking",
    term_hint: "Skandinavien",
  },
  {
    term: "Zick-Zack-Linie",
    countries: ["Großbritannien", "Singapur", "Malaysia"],
    description: "Parkverbot vor Ampeln/Zebrastreifen.",
    category: "Marking",
    term_hint: "UK oder ehemaliges britisches Territorium",
  },
  {
    term: "Lange Strichellinie",
    countries: ["Schweden"],
    description: "Markante Linienführung.",
    category: "Marking",
    term_hint: "Skandinavien",
  },
  {
    term: "Keine Mittellinie",
    countries: ["Südkorea", "Japan"],
    description: "Oft in ländlichen Regionen.",
    category: "Marking",
    term_hint: "Ostasien",
  },
  {
    term: "Bordstein (Rot-Weiß)",
    countries: ["Peru", "Ecuador", "Japan"],
    description: "Parkverbotszonen.",
    category: "Marking",
    term_hint: "Südamerika oder Ostasien",
  },
  {
    term: "Bordstein (Gelb-Schwarz)",
    countries: ["Indien", "Bangladesch", "Großbritannien"],
    description: "Markierung an Rändern.",
    category: "Marking",
    term_hint: "Südasien oder UK",
  },
  {
    term: "Blaue Parkplätze",
    countries: ["Italien", "Spanien"],
    description: "Kostenpflichtige Zonen.",
    category: "Marking",
    term_hint: "Südeuropa",
  },
  {
    term: "Grüner Radweg",
    countries: ["Dänemark", "Deutschland"],
    description: "Farbige Radwege.",
    category: "Marking",
    term_hint: "Mittel- oder Nordeuropa",
  },
  {
    term: "Straßenreflektoren",
    countries: ["Großbritannien", "Australien", "Neuseeland"],
    description: "Eingelassene Marker (Cat's Eyes).",
    category: "Marking",
    term_hint: "Britischer Einflussbereich",
  },
  {
    term: "Gelber Zebrastreifen",
    countries: ["Schweiz", "Island"],
    description: "Fußgängerüberwege in Gelb.",
    category: "Marking",
    term_hint: "Europa (Alpen oder hoher Norden)",
  },
  {
    term: "Doppelte weiße Mitte",
    countries: ["Italien", "Schweiz", "Kroatien"],
    description: "Häufig auf Bergstraßen.",
    category: "Marking",
    term_hint: "Südeuropa (oft gebirgig)",
  },

  // --- NATURE ---
  {
    term: "Rote Erde",
    countries: ["Brasilien", "Australien", "Kenia", "Sri Lanka"],
    description: "Markanter eisenhaltiger Boden.",
    category: "Nature",
    term_hint: "Südhalbkugel oder Tropen",
  },
  {
    term: "Vulkangestein",
    countries: ["Island", "Spanien (Kanaren)"],
    description: "Erkaltete Lavafelder.",
    category: "Nature",
    term_hint: "Nordeuropa oder subtropische Inseln",
  },
  {
    term: "Araukarien (Bäume)",
    countries: ["Brasilien", "Chile"],
    description: "Auffällige schirmförmige Nadelbäume.",
    category: "Nature",
    term_hint: "Südamerika",
  },
  {
    term: "Baobabs (Bäume)",
    countries: ["Senegal", "Botswana", "Madagaskar"],
    description: "Massive dicke Stämme.",
    category: "Nature",
    term_hint: "Afrika",
  },
  {
    term: "Eukalyptus",
    countries: ["Australien", "Portugal", "Spanien"],
    description: "Helle Rinde, hängende Blätter.",
    category: "Nature",
    term_hint: "Ozeanien oder Iberische Halbinsel",
  },
  {
    term: "Birkenwald",
    countries: ["Russland", "Finnland", "Baltikum"],
    description: "Nordische Vegetation.",
    category: "Nature",
    term_hint: "Nord- und Osteuropa",
  },
  {
    term: "Olivenhain",
    countries: ["Griechenland", "Spanien", "Tunesien"],
    description: "Mittelmeer-Landwirtschaft.",
    category: "Nature",
    term_hint: "Mittelmeerraum",
  },
  {
    term: "Reisterrassen",
    countries: ["Indonesien", "Philippinen", "Vietnam"],
    description: "Stufen am Hang.",
    category: "Nature",
    term_hint: "Südostasien",
  },
  {
    term: "Ölpalmen-Plantage",
    countries: ["Malaysia", "Indonesien"],
    description: "Monokulturen.",
    category: "Nature",
    term_hint: "Südostasien",
  },
  {
    term: "Große Kakteen",
    countries: ["Mexiko", "Peru", "USA"],
    description: "Wüstenvegetation.",
    category: "Nature",
    term_hint: "Nord- oder Südamerika (Wüste)",
  },
  {
    term: "Karst-Felsen",
    countries: ["Thailand", "Vietnam"],
    description: "Kalksteinformationen.",
    category: "Nature",
    term_hint: "Südostasien",
  },
  {
    term: "Rote Canyons",
    countries: ["USA (Utah)", "Australien"],
    description: "Wüstenfelsen.",
    category: "Nature",
    term_hint: "Nordamerika oder Ozeanien",
  },
  {
    term: "Moos-Tundra",
    countries: ["Island", "Färöer Inseln", "Grönland"],
    description: "Extreme Klimazonen.",
    category: "Nature",
    term_hint: "Weit im Norden Europas",
  },
  {
    term: "Bananenstauden",
    countries: ["Kambodscha", "Uganda", "Ecuador"],
    description: "Tropische Landwirtschaft.",
    category: "Nature",
    term_hint: "Tropen (Afrika, Südamerika oder Südostasien)",
  },
  {
    term: "Indian Summer",
    countries: ["Kanada", "USA", "Japan"],
    description: "Saisonale Herbstlaub-Färbung.",
    category: "Nature",
    term_hint: "Nordamerika oder Ostasien",
  },
  {
    term: "Baumfarne",
    countries: ["Neuseeland"],
    description: "Palmenartige Farne.",
    category: "Nature",
    term_hint: "Ozeanien",
  },

  // --- PLATE ---
  {
    term: "Kennzeichen: Gelb/Gelb",
    countries: ["Niederlande", "Luxemburg", "Israel", "Kolumbien"],
    description: "Vorne und hinten gelb.",
    category: "Plate",
    term_hint: "Westeuropa, Naher Osten oder Südamerika",
  },
  {
    term: "Kennzeichen: Hinten Gelb",
    countries: ["Großbritannien", "Frankreich (alt)", "Zypern"],
    description: "Vorne weiß, hinten gelb.",
    category: "Plate",
    term_hint: "Westeuropa / Britischer Einfluss",
  },
  {
    term: "Grünes Kennzeichen",
    countries: ["Norwegen"],
    description: "Nutzfahrzeuge.",
    category: "Plate",
    term_hint: "Skandinavien",
  },
  {
    term: "Kennz.: 2 blaue Streifen",
    countries: ["Italien", "Albanien", "Frankreich"],
    description: "Euroband links und rechts.",
    category: "Plate",
    term_hint: "Süd-/Westeuropa",
  },
  {
    term: "Kennzeichen: Rot links",
    countries: ["Kirgisistan"],
    description: "Markanter Akzent.",
    category: "Plate",
    term_hint: "Zentralasien",
  },
  {
    term: "Kennzeichen: Gelb rechts",
    countries: ["Portugal"],
    description: "Datumsanzeige bei älteren Schildern.",
    category: "Plate",
    term_hint: "Südwesteuropa",
  },
  {
    term: "Kennzeichen: Rote Schrift",
    countries: ["Belgien"],
    description: "Diplomaten oder Standard-BE.",
    category: "Plate",
    term_hint: "Westeuropa",
  },
  {
    term: "Kurzes Kennzeichen",
    countries: ["USA", "Japan", "Ecuador"],
    description: "Kein Euro-Format.",
    category: "Plate",
    term_hint: "Amerika oder Asien",
  },
  {
    term: "Weißes Euro-Kennzeichen",
    countries: ["Polen", "Spanien", "Rumänien"],
    description: "Euro-Standard ohne Extras.",
    category: "Plate",
    term_hint: "Europa",
  },
  {
    term: "Kein Front-Kennzeichen",
    countries: ["USA (diverse Staaten)", "Kanada"],
    description: "In vielen US-Staaten legal.",
    category: "Plate",
    term_hint: "Nordamerika",
  },
  {
    term: "Schwarzes Kennzeichen",
    countries: ["Indonesien", "Malaysia"],
    description: "Standard in SOA (weiße Schrift).",
    category: "Plate",
    term_hint: "Südostasien",
  },
  {
    term: "Rotes Kennzeichen",
    countries: ["Indien", "Vereinigte Arabische Emirate"],
    description: "Besonderer Status (Diplomat).",
    category: "Plate",
    term_hint: "Asien / Naher Osten",
  },

  // --- CAMERA ---
  {
    term: "Halo (Himmel)",
    countries: ["USA", "Kanada", "Australien", "Südafrika"],
    description: "Gen 2 Kamera Schatten.",
    category: "Camera",
    term_hint: "Nordamerika, Ozeanien oder Südafrika",
  },
  {
    term: "Niedrige Kamera",
    countries: ["Japan", "Schweiz"],
    description: "Augenhöhe mit PKWs.",
    category: "Camera",
    term_hint: "Ostasien oder Mitteleuropa",
  },
  {
    term: "Lila Farbstich",
    countries: ["Südkorea", "Taiwan"],
    description: "Gen 4 Artefakt.",
    category: "Camera",
    term_hint: "Ostasien",
  },
  {
    term: "Kamera-Konfetti",
    countries: ["Nigeria"],
    description: "Schmutz auf der Linse.",
    category: "Camera",
    term_hint: "Westafrika",
  },
  {
    term: "Trekker-Schatten",
    countries: ["Venedig", "Nationalparks"],
    description: "Fußgänger mit Kamera-Rucksack.",
    category: "Camera",
    term_hint: "Orte ohne Autos (Altstädte/Parks)",
  },
  {
    term: "Winter / Schnee",
    countries: ["Bulgarien", "Ungarn", "Finnland"],
    description: "Saisonale Coverage.",
    category: "Camera",
    term_hint: "Osteuropa oder Skandinavien",
  },
  {
    term: "Boot-Aufnahme",
    countries: ["Grönland", "Amazonas (Brasilien)"],
    description: "Wasser-Street-View.",
    category: "Camera",
    term_hint: "Arktis oder Südamerika (Flüsse)",
  },
  {
    term: "Overcast (Düster)",
    countries: ["Russland", "Polen", "Großbritannien"],
    description: "Schlechtes Wetter beim Fahren.",
    category: "Camera",
    term_hint: "Nord- oder Osteuropa",
  },
  {
    term: "Golden Hour",
    countries: ["Südafrika", "Mexiko"],
    description: "Sonnenuntergang / Später Nachmittag.",
    category: "Camera",
    term_hint: "Südliches Afrika oder Zentralamerika",
  },
  {
    term: "Zensur-Kreis (unten)",
    countries: ["Katar", "Vereinigte Arabische Emirate"],
    description: "Riesiger Blur-Kreis.",
    category: "Camera",
    term_hint: "Naher Osten",
  },
  {
    term: "Drohnen-Schatten",
    countries: ["Diverse Sehenswürdigkeiten"],
    description: "Luftaufnahmen.",
    category: "Camera",
    term_hint: "Oft bei Denkmälern/Parks",
  },
];

export const GeoGuessrMetaEn: GeoMeta[] = [
  // --- VEHICLE ---
  {
    term: "Black Snorkel",
    countries: ["Kenya", "Mongolia"],
    description: "Air intake pipe on the front right.",
    category: "Vehicle",
    term_hint: "East Africa or Central Asian Steppe",
  },
  {
    term: "Roof Rack + Tire",
    countries: ["Guatemala"],
    description: "Heavy duty rack with a spare tire.",
    category: "Vehicle",
    term_hint: "Central America",
  },
  {
    term: "Thin Roof Bars",
    countries: ["Kyrgyzstan", "Laos", "Mongolia"],
    description: "Thin, minimal roof bars.",
    category: "Vehicle",
    term_hint: "Central or Southeast Asia",
  },
  {
    term: "Roof Tape (Front)",
    countries: ["Ghana"],
    description: "Tape on the front right of the rack.",
    category: "Vehicle",
    term_hint: "West Africa",
  },
  {
    term: "Roof Tape (Back)",
    countries: ["Ghana"],
    description: "Rare variant on the rear of the rack.",
    category: "Vehicle",
    term_hint: "West Africa",
  },
  {
    term: "White Side Mirrors",
    countries: ["Nigeria"],
    description: "Google car mirrors in frame.",
    category: "Vehicle",
    term_hint: "West Africa",
  },
  {
    term: "Black Side Mirrors",
    countries: ["Argentina", "Uruguay", "Peru"],
    description: "Mirrors of black Google cars.",
    category: "Vehicle",
    term_hint: "South America",
  },
  {
    term: "White Pickup Bed",
    countries: ["Thailand", "Philippines"],
    description: "Back of a pickup visible at the bottom.",
    category: "Vehicle",
    term_hint: "Southeast Asia",
  },
  {
    term: "Roll Bars (Rear)",
    countries: ["Senegal", "Nigeria"],
    description: "Metal bars protruding over the truck bed.",
    category: "Vehicle",
    term_hint: "West Africa",
  },
  {
    term: "Helmet Shadow",
    countries: ["Vietnam"],
    description: "The driver of the Street View bike.",
    category: "Vehicle",
    term_hint: "Southeast Asia",
  },
  {
    term: "Camping Gear",
    countries: ["Mongolia"],
    description: "Tarps and equipment on the pickup.",
    category: "Vehicle",
    term_hint: "Central Asia",
  },
  {
    term: "Ball Antenna",
    countries: ["Australia"],
    description: "Radio antenna on the car.",
    category: "Vehicle",
    term_hint: "Oceania",
  },
  {
    term: "Police/Military Escort",
    countries: ["Kenya", "Nigeria", "Tunisia"],
    description: "Vehicle driving ahead or behind.",
    category: "Vehicle",
    term_hint: "Africa",
  },
  {
    term: "Red Google Car",
    countries: ["Ukraine"],
    description: "Red hood visible.",
    category: "Vehicle",
    term_hint: "Eastern Europe",
  },
  {
    term: "Front Car Blur",
    countries: ["Sri Lanka", "Indonesia"],
    description: "Heavily censored car hood.",
    category: "Vehicle",
    term_hint: "South or Southeast Asia",
  },
  {
    term: "Tuk-Tuk",
    countries: ["India", "Bangladesh", "Sri Lanka"],
    description: "Three-wheeled taxis in traffic.",
    category: "Vehicle",
    term_hint: "South Asia",
  },
  {
    term: "Yellow Taxi",
    countries: ["Colombia", "Peru", "New York (USA)"],
    description: "Specific taxi colors.",
    category: "Vehicle",
    term_hint: "Americas",
  },

  // --- INFRASTRUCTURE ---
  {
    term: "Ladder Pole (Concrete)",
    countries: ["Poland", "Hungary", "Romania"],
    description: "Poles with rectangular holes.",
    category: "Infrastructure",
    term_hint: "Eastern Europe",
  },
  {
    term: "Wooden Pole + Metal Hat",
    countries: ["Japan"],
    description: "Rain covers on utility poles.",
    category: "Infrastructure",
    term_hint: "East Asia",
  },
  {
    term: "Bollard (Red Ring)",
    countries: ["France", "Spain"],
    description: "Classic roadside post.",
    category: "Infrastructure",
    term_hint: "Southwestern Europe",
  },
  {
    term: "Bollard (Yellow Reflector)",
    countries: ["Denmark"],
    description: "Often combined with a red line.",
    category: "Infrastructure",
    term_hint: "Northern Europe / Scandinavia",
  },
  {
    term: "A-Pole (Wood)",
    countries: ["Finland", "Sweden"],
    description: "Supported utility poles.",
    category: "Infrastructure",
    term_hint: "Scandinavia",
  },
  {
    term: "A-Pole (Concrete)",
    countries: ["Brazil", "Chile"],
    description: "South American support poles.",
    category: "Infrastructure",
    term_hint: "South America",
  },
  {
    term: "Hexagon Pole",
    countries: ["Mexico", "Colombia"],
    description: "Poles with a 6-sided cross-section.",
    category: "Infrastructure",
    term_hint: "Latin America",
  },
  {
    term: "Blue Sign Back",
    countries: ["France"],
    description: "Back of directional signs.",
    category: "Infrastructure",
    term_hint: "Western Europe",
  },
  {
    term: "Yellow Sign Back",
    countries: ["Greece"],
    description: "Back of town/warning signs.",
    category: "Infrastructure",
    term_hint: "Southern Europe",
  },
  {
    term: "Painted Pole Base",
    countries: ["Indonesia", "Malaysia", "Pakistan"],
    description: "Painted bottom meters.",
    category: "Infrastructure",
    term_hint: "Southeast or South Asia",
  },
  {
    term: "Striped Pole (Yellow/Black)",
    countries: ["Taiwan", "South Korea"],
    description: "Warning colors on poles.",
    category: "Infrastructure",
    term_hint: "East Asia",
  },
  {
    term: "Giant Water Tower",
    countries: ["USA"],
    description: "Often painted with the town's name.",
    category: "Infrastructure",
    term_hint: "North America",
  },
  {
    term: "Concrete Bus Stop",
    countries: ["Russia", "Ukraine", "Baltics"],
    description: "Soviet architecture.",
    category: "Infrastructure",
    term_hint: "Former Soviet States",
  },
  {
    term: "Yellow Fire Hydrant",
    countries: ["USA", "Canada"],
    description: "Typical street hydrants.",
    category: "Infrastructure",
    term_hint: "North America",
  },
  {
    term: "Red Brick Houses",
    countries: ["United Kingdom", "Netherlands"],
    description: "Very uniform architecture.",
    category: "Infrastructure",
    term_hint: "Northwestern Europe",
  },
  {
    term: "Bollard (Black Slash)",
    countries: ["Austria"],
    description: "Post with a diagonal line and dots.",
    category: "Infrastructure",
    term_hint: "Central Europe (Alps)",
  },

  // --- MARKING ---
  {
    term: "Yellow Outer Line",
    countries: ["South Africa", "Botswana", "Lesotho", "Eswatini"],
    description: "Road edge markings.",
    category: "Marking",
    term_hint: "Southern Africa",
  },
  {
    term: "Double Yellow Center",
    countries: ["USA", "Canada", "Mexico", "Brazil"],
    description: "Separates opposing traffic.",
    category: "Marking",
    term_hint: "Americas",
  },
  {
    term: "Single Yellow Center",
    countries: ["Norway"],
    description: "Scandinavian exception.",
    category: "Marking",
    term_hint: "Scandinavia",
  },
  {
    term: "Zig-Zag Line",
    countries: ["United Kingdom", "Singapore", "Malaysia"],
    description: "No parking near crossings.",
    category: "Marking",
    term_hint: "UK or former British territories in Asia",
  },
  {
    term: "Long Dashed Outer Line",
    countries: ["Sweden"],
    description: "Distinct edge line pattern.",
    category: "Marking",
    term_hint: "Scandinavia",
  },
  {
    term: "No Center Line",
    countries: ["South Korea", "Japan"],
    description: "Common in rural areas.",
    category: "Marking",
    term_hint: "East Asia",
  },
  {
    term: "Curb (Red-White)",
    countries: ["Peru", "Ecuador", "Japan"],
    description: "No parking zones.",
    category: "Marking",
    term_hint: "South America or East Asia",
  },
  {
    term: "Curb (Yellow-Black)",
    countries: ["India", "Bangladesh", "UK"],
    description: "Edge markings.",
    category: "Marking",
    term_hint: "South Asia or UK",
  },
  {
    term: "Blue Parking Bays",
    countries: ["Italy", "Spain"],
    description: "Paid parking zones.",
    category: "Marking",
    term_hint: "Southern Europe",
  },
  {
    term: "Green Bike Lane",
    countries: ["Denmark", "Germany"],
    description: "Colored cycling paths.",
    category: "Marking",
    term_hint: "Central or Northern Europe",
  },
  {
    term: "Cat's Eyes (Reflectors)",
    countries: ["United Kingdom", "Australia", "New Zealand"],
    description: "Embedded markers.",
    category: "Marking",
    term_hint: "British influence (UK/Oceania)",
  },
  {
    term: "Yellow Zebra Crossing",
    countries: ["Switzerland", "Iceland"],
    description: "Zebra crossings painted yellow.",
    category: "Marking",
    term_hint: "Europe (Alps or far North)",
  },
  {
    term: "Double White Center",
    countries: ["Italy", "Switzerland", "Croatia"],
    description: "Common on mountain roads.",
    category: "Marking",
    term_hint: "Southern Europe (often mountainous)",
  },

  // --- NATURE ---
  {
    term: "Red Soil",
    countries: ["Brazil", "Australia", "Kenya", "Sri Lanka"],
    description: "Distinctive iron dirt.",
    category: "Nature",
    term_hint: "Southern Hemisphere or Tropics",
  },
  {
    term: "Volcanic Rock",
    countries: ["Iceland", "Spain (Canaries)"],
    description: "Cooled lava fields.",
    category: "Nature",
    term_hint: "Northern Europe or Subtropical Islands",
  },
  {
    term: "Araucaria (Trees)",
    countries: ["Brazil", "Chile"],
    description: "Striking pine trees.",
    category: "Nature",
    term_hint: "South America",
  },
  {
    term: "Baobab (Trees)",
    countries: ["Senegal", "Botswana", "Madagascar"],
    description: "Massive thick trunks.",
    category: "Nature",
    term_hint: "Africa",
  },
  {
    term: "Eucalyptus",
    countries: ["Australia", "Portugal", "Spain"],
    description: "Light bark, hanging leaves.",
    category: "Nature",
    term_hint: "Oceania or Iberian Peninsula",
  },
  {
    term: "Birch Forest",
    countries: ["Russia", "Finland", "Baltics"],
    description: "Nordic vegetation.",
    category: "Nature",
    term_hint: "Northern and Eastern Europe",
  },
  {
    term: "Olive Grove",
    countries: ["Greece", "Spain", "Tunisia"],
    description: "Mediterranean agriculture.",
    category: "Nature",
    term_hint: "Mediterranean Region",
  },
  {
    term: "Rice Terraces",
    countries: ["Indonesia", "Philippines", "Vietnam"],
    description: "Steps on a hillside.",
    category: "Nature",
    term_hint: "Southeast Asia",
  },
  {
    term: "Palm Oil Plantation",
    countries: ["Malaysia", "Indonesia"],
    description: "Monocultures.",
    category: "Nature",
    term_hint: "Southeast Asia",
  },
  {
    term: "Large Cacti",
    countries: ["Mexico", "Peru", "USA"],
    description: "Desert vegetation.",
    category: "Nature",
    term_hint: "Americas (Deserts)",
  },
  {
    term: "Karst Mountains",
    countries: ["Thailand", "Vietnam"],
    description: "Limestone formations.",
    category: "Nature",
    term_hint: "Southeast Asia",
  },
  {
    term: "Red Rock Canyons",
    countries: ["USA (Utah)", "Australia"],
    description: "Desert rocks.",
    category: "Nature",
    term_hint: "North America or Oceania",
  },
  {
    term: "Moss Tundra",
    countries: ["Iceland", "Faroe Islands", "Greenland"],
    description: "Extreme climates.",
    category: "Nature",
    term_hint: "Far Northern Europe",
  },
  {
    term: "Banana Plants",
    countries: ["Cambodia", "Uganda", "Ecuador"],
    description: "Tropical agriculture.",
    category: "Nature",
    term_hint: "Tropics (Africa, South America, or Southeast Asia)",
  },
  {
    term: "Indian Summer",
    countries: ["Canada", "USA", "Japan"],
    description: "Seasonal autumn leaves.",
    category: "Nature",
    term_hint: "North America or East Asia",
  },
  {
    term: "Tree Ferns",
    countries: ["New Zealand"],
    description: "Palm-like ferns.",
    category: "Nature",
    term_hint: "Oceania",
  },

  // --- PLATE ---
  {
    term: "Plate: Yellow/Yellow",
    countries: ["Netherlands", "Luxembourg", "Israel", "Colombia"],
    description: "Completely yellow front & back.",
    category: "Plate",
    term_hint: "Western Europe, Middle East, or South America",
  },
  {
    term: "Plate: Yellow Back",
    countries: ["United Kingdom", "France (old)", "Cyprus"],
    description: "Front white, rear yellow.",
    category: "Plate",
    term_hint: "Western Europe / British Influence",
  },
  {
    term: "Green License Plate",
    countries: ["Norway"],
    description: "Commercial vehicles.",
    category: "Plate",
    term_hint: "Scandinavia",
  },
  {
    term: "Plate: 2 Blue Strips",
    countries: ["Italy", "Albania", "France"],
    description: "Euroband left and right.",
    category: "Plate",
    term_hint: "Southern/Western Europe",
  },
  {
    term: "Plate: Red Left",
    countries: ["Kyrgyzstan"],
    description: "Distinctive accent.",
    category: "Plate",
    term_hint: "Central Asia",
  },
  {
    term: "Plate: Yellow Right",
    countries: ["Portugal"],
    description: "Date display on older plates.",
    category: "Plate",
    term_hint: "Southwestern Europe",
  },
  {
    term: "Plate: Red Font",
    countries: ["Belgium"],
    description: "Diplomatic or standard BE.",
    category: "Plate",
    term_hint: "Western Europe",
  },
  {
    term: "Short/Square Plate",
    countries: ["USA", "Japan", "Ecuador"],
    description: "Non-Euro format.",
    category: "Plate",
    term_hint: "Americas or Asia",
  },
  {
    term: "White Euro Plate",
    countries: ["Poland", "Spain", "Romania"],
    description: "Euro standard, no extras.",
    category: "Plate",
    term_hint: "Europe",
  },
  {
    term: "No Front Plate",
    countries: ["USA (various states)", "Canada"],
    description: "Legal in many US states.",
    category: "Plate",
    term_hint: "North America",
  },
  {
    term: "Black License Plate",
    countries: ["Indonesia", "Malaysia"],
    description: "Standard in SEA.",
    category: "Plate",
    term_hint: "Southeast Asia",
  },
  {
    term: "Red Diplomatic Plate",
    countries: ["India", "UAE"],
    description: "Special status.",
    category: "Plate",
    term_hint: "Asia / Middle East",
  },

  // --- CAMERA ---
  {
    term: "Halo (Sky)",
    countries: ["USA", "Canada", "Australia", "South Africa"],
    description: "Gen 2 camera shadow.",
    category: "Camera",
    term_hint: "North America, Oceania, or South Africa",
  },
  {
    term: "Low Camera",
    countries: ["Japan", "Switzerland"],
    description: "Eye-level with cars.",
    category: "Camera",
    term_hint: "East Asia or Central Europe",
  },
  {
    term: "Purple Tint",
    countries: ["South Korea", "Taiwan"],
    description: "Gen 4 artifact.",
    category: "Camera",
    term_hint: "East Asia",
  },
  {
    term: "Camera Dirt (Confetti)",
    countries: ["Nigeria"],
    description: "Spots on the lens.",
    category: "Camera",
    term_hint: "West Africa",
  },
  {
    term: "Trekker Shadow",
    countries: ["Venice", "National Parks"],
    description: "Pedestrian with backpack.",
    category: "Camera",
    term_hint: "Car-free zones (Old towns/Parks)",
  },
  {
    term: "Winter / Snow",
    countries: ["Bulgaria", "Hungary", "Finland"],
    description: "Seasonal coverage.",
    category: "Camera",
    term_hint: "Eastern Europe or Scandinavia",
  },
  {
    term: "Boat Footage",
    countries: ["Greenland", "Amazon (Brazil)"],
    description: "Water Street View.",
    category: "Camera",
    term_hint: "Arctic or South America (Rivers)",
  },
  {
    term: "Overcast (Gloomy)",
    countries: ["Russia", "Poland", "United Kingdom"],
    description: "Bad weather driving.",
    category: "Camera",
    term_hint: "Northern or Eastern Europe",
  },
  {
    term: "Golden Hour",
    countries: ["South Africa", "Mexico"],
    description: "Late afternoon coverage.",
    category: "Camera",
    term_hint: "Southern Africa or Central America",
  },
  {
    term: "Censorship Circle",
    countries: ["Qatar", "UAE"],
    description: "Giant black blur at bottom.",
    category: "Camera",
    term_hint: "Middle East",
  },
  {
    term: "Drone Shadow",
    countries: ["Various Landmarks"],
    description: "Aerial view.",
    category: "Camera",
    term_hint: "Often near monuments or parks",
  },
];
