/*
================================================================================
GEOGUESSR META
================================================================================
Canonical list of GeoGuessr "meta" clues (region-revealing details a player can
hunt for in Street View). The facts (countries / category / description) are
stored ONCE; only the player-facing `term` (the bingo label) and `term_hint`
(the region hint) are localized per language. Add a language by adding its key
to every `term` / `term_hint` map — TypeScript enforces completeness via
Record<CategoryLanguage, string>.
================================================================================
*/

import type { CategoryLanguage } from './i18n/locales';

export interface GeoMeta {
    countries: string[];
    description: string;
    category: 'Vehicle' | 'Camera' | 'Infrastructure' | 'Nature' | 'Plate' | 'Marking';
    term: Record<CategoryLanguage, string>;
    term_hint: Record<CategoryLanguage, string>;
}

export const geoGuessrMeta: GeoMeta[] = [
    // --- VEHICLE ---
    {
        category: 'Vehicle',
        countries: ['Kenya', 'Mongolia'],
        description: 'Air intake pipe on the front right.',
        term: { german: 'Schwarzer Schnorchel', english: 'Black Snorkel', spanish: 'Esnórquel negro', french: 'Schnorkel noir', chinese: '黑色通气管' },
        term_hint: { german: 'Ostafrika oder zentralasiatische Steppe', english: 'East Africa or Central Asian Steppe', spanish: 'África Oriental o estepa de Asia Central', french: "Afrique de l'Est ou steppe d'Asie centrale", chinese: '东非或中亚草原' },
    },
    {
        category: 'Vehicle',
        countries: ['Guatemala'],
        description: 'Heavy duty rack with a spare tire.',
        term: { german: 'Dachträger + Reifen', english: 'Roof Rack + Tire', spanish: 'Baca + neumático', french: 'Galerie + pneu', chinese: '车顶架 + 备胎' },
        term_hint: { german: 'Zentralamerika', english: 'Central America', spanish: 'América Central', french: 'Amérique centrale', chinese: '中美洲' },
    },
    {
        category: 'Vehicle',
        countries: ['Kyrgyzstan', 'Laos', 'Mongolia'],
        description: 'Thin, minimal roof bars.',
        term: { german: 'Dünne Dachstangen', english: 'Thin Roof Bars', spanish: 'Barras de techo finas', french: 'Barres de toit fines', chinese: '细车顶杆' },
        term_hint: { german: 'Zentral- oder Südostasien', english: 'Central or Southeast Asia', spanish: 'Asia Central o Sudeste Asiático', french: 'Asie centrale ou du Sud-Est', chinese: '中亚或东南亚' },
    },
    {
        category: 'Vehicle',
        countries: ['Ghana'],
        description: 'Tape on the front right of the rack.',
        term: { german: 'Schwarzes Tape (Dach)', english: 'Roof Tape (Front)', spanish: 'Cinta en la baca (delante)', french: 'Ruban sur galerie (avant)', chinese: '车顶胶带（前）' },
        term_hint: { german: 'Westafrika', english: 'West Africa', spanish: 'África Occidental', french: "Afrique de l'Ouest", chinese: '西非' },
    },
    {
        category: 'Vehicle',
        countries: ['Ghana'],
        description: 'Rare variant on the rear of the rack.',
        term: { german: 'Rotes Tape (Dach)', english: 'Roof Tape (Back)', spanish: 'Cinta en la baca (detrás)', french: 'Ruban sur galerie (arrière)', chinese: '车顶胶带（后）' },
        term_hint: { german: 'Westafrika', english: 'West Africa', spanish: 'África Occidental', french: "Afrique de l'Ouest", chinese: '西非' },
    },
    {
        category: 'Vehicle',
        countries: ['Nigeria'],
        description: 'Google car mirrors in frame.',
        term: { german: 'Weiße Seitenspiegel', english: 'White Side Mirrors', spanish: 'Retrovisores blancos', french: 'Rétroviseurs blancs', chinese: '白色后视镜' },
        term_hint: { german: 'Westafrika', english: 'West Africa', spanish: 'África Occidental', french: "Afrique de l'Ouest", chinese: '西非' },
    },
    {
        category: 'Vehicle',
        countries: ['Argentina', 'Uruguay', 'Peru'],
        description: 'Mirrors of black Google cars.',
        term: { german: 'Schwarze Seitenspiegel', english: 'Black Side Mirrors', spanish: 'Retrovisores negros', french: 'Rétroviseurs noirs', chinese: '黑色后视镜' },
        term_hint: { german: 'Südamerika', english: 'South America', spanish: 'América del Sur', french: 'Amérique du Sud', chinese: '南美洲' },
    },
    {
        category: 'Vehicle',
        countries: ['Thailand', 'Philippines'],
        description: 'Back of a pickup visible at the bottom.',
        term: { german: 'Weißer Pickup (Heck)', english: 'White Pickup Bed', spanish: 'Caja de pickup blanca', french: 'Benne de pick-up blanche', chinese: '白色皮卡车厢' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Vehicle',
        countries: ['Senegal', 'Nigeria'],
        description: 'Metal bars protruding over the truck bed.',
        term: { german: 'Roll Bars (Heck)', english: 'Roll Bars (Rear)', spanish: 'Barras antivuelco (traseras)', french: 'Arceaux (arrière)', chinese: '后防滚架' },
        term_hint: { german: 'Westafrika', english: 'West Africa', spanish: 'África Occidental', french: "Afrique de l'Ouest", chinese: '西非' },
    },
    {
        category: 'Vehicle',
        countries: ['Vietnam'],
        description: 'The driver of the Street View bike.',
        term: { german: 'Helm-Schatten', english: 'Helmet Shadow', spanish: 'Sombra del casco', french: 'Ombre du casque', chinese: '头盔阴影' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Vehicle',
        countries: ['Mongolia'],
        description: 'Tarps and equipment on the pickup.',
        term: { german: 'Camping-Ausrüstung', english: 'Camping Gear', spanish: 'Equipo de camping', french: 'Matériel de camping', chinese: '露营装备' },
        term_hint: { german: 'Zentralasien', english: 'Central Asia', spanish: 'Asia Central', french: 'Asie centrale', chinese: '中亚' },
    },
    {
        category: 'Vehicle',
        countries: ['Australia'],
        description: 'Radio antenna on the car.',
        term: { german: 'Kugel-Antenne', english: 'Ball Antenna', spanish: 'Antena de bola', french: 'Antenne à boule', chinese: '球形天线' },
        term_hint: { german: 'Ozeanien', english: 'Oceania', spanish: 'Oceanía', french: 'Océanie', chinese: '大洋洲' },
    },
    {
        category: 'Vehicle',
        countries: ['Kenya', 'Nigeria', 'Tunisia'],
        description: 'Vehicle driving ahead or behind.',
        term: { german: 'Eskorte (Polizei)', english: 'Police/Military Escort', spanish: 'Escolta policial/militar', french: 'Escorte police/militaire', chinese: '警车/军车护卫' },
        term_hint: { german: 'Afrika', english: 'Africa', spanish: 'África', french: 'Afrique', chinese: '非洲' },
    },
    {
        category: 'Vehicle',
        countries: ['Ukraine'],
        description: 'Red hood visible.',
        term: { german: 'Rotes Google-Auto', english: 'Red Google Car', spanish: 'Coche de Google rojo', french: 'Voiture Google rouge', chinese: '红色谷歌车' },
        term_hint: { german: 'Osteuropa', english: 'Eastern Europe', spanish: 'Europa del Este', french: "Europe de l'Est", chinese: '东欧' },
    },
    {
        category: 'Vehicle',
        countries: ['Sri Lanka', 'Indonesia'],
        description: 'Heavily censored car hood.',
        term: { german: 'Front-Blur (Auto)', english: 'Front Car Blur', spanish: 'Capó muy censurado', french: 'Capot très flouté', chinese: '车头模糊' },
        term_hint: { german: 'Süd- oder Südostasien', english: 'South or Southeast Asia', spanish: 'Asia del Sur o Sudeste Asiático', french: 'Asie du Sud ou du Sud-Est', chinese: '南亚或东南亚' },
    },
    {
        category: 'Vehicle',
        countries: ['India', 'Bangladesh', 'Sri Lanka'],
        description: 'Three-wheeled taxis in traffic.',
        term: { german: 'Tuk-Tuk', english: 'Tuk-Tuk', spanish: 'Tuk-tuk', french: 'Tuk-tuk', chinese: '嘟嘟车' },
        term_hint: { german: 'Südasien', english: 'South Asia', spanish: 'Asia del Sur', french: 'Asie du Sud', chinese: '南亚' },
    },
    {
        category: 'Vehicle',
        countries: ['Colombia', 'Peru', 'New York (USA)'],
        description: 'Specific taxi colors.',
        term: { german: 'Gelbes Taxi', english: 'Yellow Taxi', spanish: 'Taxi amarillo', french: 'Taxi jaune', chinese: '黄色出租车' },
        term_hint: { german: 'Nord- oder Südamerika', english: 'Americas', spanish: 'América', french: 'Amériques', chinese: '美洲' },
    },

    // --- INFRASTRUCTURE ---
    {
        category: 'Infrastructure',
        countries: ['Poland', 'Hungary', 'Romania'],
        description: 'Poles with rectangular holes.',
        term: { german: 'Leitermast (Beton)', english: 'Ladder Pole (Concrete)', spanish: 'Poste de escalera (hormigón)', french: 'Poteau échelle (béton)', chinese: '梯形混凝土电杆' },
        term_hint: { german: 'Osteuropa', english: 'Eastern Europe', spanish: 'Europa del Este', french: "Europe de l'Est", chinese: '东欧' },
    },
    {
        category: 'Infrastructure',
        countries: ['Japan'],
        description: 'Rain covers on utility poles.',
        term: { german: 'Holzmast + Metalldach', english: 'Wooden Pole + Metal Hat', spanish: 'Poste de madera + sombrero metálico', french: 'Poteau bois + chapeau métal', chinese: '木电杆 + 金属帽' },
        term_hint: { german: 'Ostasien', english: 'East Asia', spanish: 'Asia Oriental', french: "Asie de l'Est", chinese: '东亚' },
    },
    {
        category: 'Infrastructure',
        countries: ['France', 'Spain'],
        description: 'Classic roadside post.',
        term: { german: 'Pfosten (Roter Ring)', english: 'Bollard (Red Ring)', spanish: 'Baliza (anillo rojo)', french: 'Balise (anneau rouge)', chinese: '路桩（红环）' },
        term_hint: { german: 'Südwesteuropa', english: 'Southwestern Europe', spanish: 'Europa Suroccidental', french: 'Europe du Sud-Ouest', chinese: '西南欧' },
    },
    {
        category: 'Infrastructure',
        countries: ['Denmark'],
        description: 'Often combined with a red line.',
        term: { german: 'Pfosten (Gelb. Reflektor)', english: 'Bollard (Yellow Reflector)', spanish: 'Baliza (reflector amarillo)', french: 'Balise (réflecteur jaune)', chinese: '路桩（黄反光片）' },
        term_hint: { german: 'Nordeuropa / Skandinavien', english: 'Northern Europe / Scandinavia', spanish: 'Europa del Norte / Escandinavia', french: 'Europe du Nord / Scandinavie', chinese: '北欧 / 斯堪的纳维亚' },
    },
    {
        category: 'Infrastructure',
        countries: ['Finland', 'Sweden'],
        description: 'Supported utility poles.',
        term: { german: 'A-Mast (Holz)', english: 'A-Pole (Wood)', spanish: 'Poste en A (madera)', french: 'Poteau en A (bois)', chinese: 'A 形木杆' },
        term_hint: { german: 'Skandinavien', english: 'Scandinavia', spanish: 'Escandinavia', french: 'Scandinavie', chinese: '斯堪的纳维亚' },
    },
    {
        category: 'Infrastructure',
        countries: ['Brazil', 'Chile'],
        description: 'South American support poles.',
        term: { german: 'A-Mast (Beton)', english: 'A-Pole (Concrete)', spanish: 'Poste en A (hormigón)', french: 'Poteau en A (béton)', chinese: 'A 形混凝土杆' },
        term_hint: { german: 'Südamerika', english: 'South America', spanish: 'América del Sur', french: 'Amérique du Sud', chinese: '南美洲' },
    },
    {
        category: 'Infrastructure',
        countries: ['Mexico', 'Colombia'],
        description: 'Poles with a 6-sided cross-section.',
        term: { german: 'Hexagon-Mast', english: 'Hexagon Pole', spanish: 'Poste hexagonal', french: 'Poteau hexagonal', chinese: '六角形电杆' },
        term_hint: { german: 'Lateinamerika', english: 'Latin America', spanish: 'América Latina', french: 'Amérique latine', chinese: '拉丁美洲' },
    },
    {
        category: 'Infrastructure',
        countries: ['France'],
        description: 'Back of directional signs.',
        term: { german: 'Blaue Schildrückseite', english: 'Blue Sign Back', spanish: 'Reverso de señal azul', french: 'Dos de panneau bleu', chinese: '蓝色路牌背面' },
        term_hint: { german: 'Westeuropa', english: 'Western Europe', spanish: 'Europa Occidental', french: "Europe de l'Ouest", chinese: '西欧' },
    },
    {
        category: 'Infrastructure',
        countries: ['Greece'],
        description: 'Back of town/warning signs.',
        term: { german: 'Gelbe Schildrückseite', english: 'Yellow Sign Back', spanish: 'Reverso de señal amarillo', french: 'Dos de panneau jaune', chinese: '黄色路牌背面' },
        term_hint: { german: 'Südeuropa', english: 'Southern Europe', spanish: 'Europa del Sur', french: 'Europe du Sud', chinese: '南欧' },
    },
    {
        category: 'Infrastructure',
        countries: ['Indonesia', 'Malaysia', 'Pakistan'],
        description: 'Painted bottom meters.',
        term: { german: 'Mastfuß (gestreift)', english: 'Painted Pole Base', spanish: 'Base de poste pintada', french: 'Base de poteau peinte', chinese: '涂漆杆基' },
        term_hint: { german: 'Südost- oder Südasien', english: 'Southeast or South Asia', spanish: 'Sudeste o Sur de Asia', french: 'Asie du Sud-Est ou du Sud', chinese: '东南亚或南亚' },
    },
    {
        category: 'Infrastructure',
        countries: ['Taiwan', 'South Korea'],
        description: 'Warning colors on poles.',
        term: { german: 'Warnfarben-Mast', english: 'Striped Pole (Yellow/Black)', spanish: 'Poste rayado (amarillo/negro)', french: 'Poteau rayé (jaune/noir)', chinese: '黄黑条纹杆' },
        term_hint: { german: 'Ostasien', english: 'East Asia', spanish: 'Asia Oriental', french: "Asie de l'Est", chinese: '东亚' },
    },
    {
        category: 'Infrastructure',
        countries: ['USA'],
        description: "Often painted with the town's name.",
        term: { german: 'Großer Wasserturm', english: 'Giant Water Tower', spanish: 'Torre de agua gigante', french: "Château d'eau géant", chinese: '巨型水塔' },
        term_hint: { german: 'Nordamerika', english: 'North America', spanish: 'América del Norte', french: 'Amérique du Nord', chinese: '北美洲' },
    },
    {
        category: 'Infrastructure',
        countries: ['Russia', 'Ukraine', 'Baltics'],
        description: 'Soviet architecture.',
        term: { german: 'Beton-Bushaltestelle', english: 'Concrete Bus Stop', spanish: 'Parada de autobús de hormigón', french: 'Arrêt de bus en béton', chinese: '混凝土公交站' },
        term_hint: { german: 'Ehemalige Sowjetstaaten', english: 'Former Soviet States', spanish: 'Exrepúblicas soviéticas', french: 'Ex-États soviétiques', chinese: '前苏联国家' },
    },
    {
        category: 'Infrastructure',
        countries: ['USA', 'Canada'],
        description: 'Typical street hydrants.',
        term: { german: 'Gelber Hydrant', english: 'Yellow Fire Hydrant', spanish: 'Hidrante amarillo', french: "Bouche d'incendie jaune", chinese: '黄色消防栓' },
        term_hint: { german: 'Nordamerika', english: 'North America', spanish: 'América del Norte', french: 'Amérique du Nord', chinese: '北美洲' },
    },
    {
        category: 'Infrastructure',
        countries: ['United Kingdom', 'Netherlands'],
        description: 'Very uniform architecture.',
        term: { german: 'Rote Backsteinhäuser', english: 'Red Brick Houses', spanish: 'Casas de ladrillo rojo', french: 'Maisons en brique rouge', chinese: '红砖房' },
        term_hint: { german: 'Nordwesteuropa', english: 'Northwestern Europe', spanish: 'Europa Noroccidental', french: 'Europe du Nord-Ouest', chinese: '西北欧' },
    },
    {
        category: 'Infrastructure',
        countries: ['Austria'],
        description: 'Post with a diagonal line and dots.',
        term: { german: 'Pfosten (Schrägstrich)', english: 'Bollard (Black Slash)', spanish: 'Baliza (raya negra)', french: 'Balise (trait noir)', chinese: '路桩（黑斜线）' },
        term_hint: { german: 'Mitteleuropa (Alpen)', english: 'Central Europe (Alps)', spanish: 'Europa Central (Alpes)', french: 'Europe centrale (Alpes)', chinese: '中欧（阿尔卑斯）' },
    },

    // --- MARKING ---
    {
        category: 'Marking',
        countries: ['South Africa', 'Botswana', 'Lesotho', 'Eswatini'],
        description: 'Road edge markings.',
        term: { german: 'Gelbe Außenlinie', english: 'Yellow Outer Line', spanish: 'Línea exterior amarilla', french: 'Ligne extérieure jaune', chinese: '黄色边线' },
        term_hint: { german: 'Südliches Afrika', english: 'Southern Africa', spanish: 'África Austral', french: 'Afrique australe', chinese: '南部非洲' },
    },
    {
        category: 'Marking',
        countries: ['USA', 'Canada', 'Mexico', 'Brazil'],
        description: 'Separates opposing traffic.',
        term: { german: 'Doppelte gelbe Mitte', english: 'Double Yellow Center', spanish: 'Doble línea central amarilla', french: 'Double ligne centrale jaune', chinese: '双黄中线' },
        term_hint: { german: 'Nord- oder Südamerika', english: 'Americas', spanish: 'América', french: 'Amériques', chinese: '美洲' },
    },
    {
        category: 'Marking',
        countries: ['Norway'],
        description: 'Scandinavian exception.',
        term: { german: 'Einfache gelbe Mitte', english: 'Single Yellow Center', spanish: 'Línea central amarilla simple', french: 'Ligne centrale jaune simple', chinese: '单黄中线' },
        term_hint: { german: 'Skandinavien', english: 'Scandinavia', spanish: 'Escandinavia', french: 'Scandinavie', chinese: '斯堪的纳维亚' },
    },
    {
        category: 'Marking',
        countries: ['United Kingdom', 'Singapore', 'Malaysia'],
        description: 'No parking near crossings.',
        term: { german: 'Zick-Zack-Linie', english: 'Zig-Zag Line', spanish: 'Línea en zigzag', french: 'Ligne en zigzag', chinese: '锯齿线' },
        term_hint: { german: 'UK oder ehemaliges britisches Territorium', english: 'UK or former British territories in Asia', spanish: 'Reino Unido o excolonias británicas en Asia', french: 'Royaume-Uni ou ex-territoires britanniques en Asie', chinese: '英国或亚洲前英属地区' },
    },
    {
        category: 'Marking',
        countries: ['Sweden'],
        description: 'Distinct edge line pattern.',
        term: { german: 'Lange Strichellinie', english: 'Long Dashed Outer Line', spanish: 'Línea exterior de trazos largos', french: 'Ligne extérieure à longs tirets', chinese: '长虚线边线' },
        term_hint: { german: 'Skandinavien', english: 'Scandinavia', spanish: 'Escandinavia', french: 'Scandinavie', chinese: '斯堪的纳维亚' },
    },
    {
        category: 'Marking',
        countries: ['South Korea', 'Japan'],
        description: 'Common in rural areas.',
        term: { german: 'Keine Mittellinie', english: 'No Center Line', spanish: 'Sin línea central', french: 'Sans ligne centrale', chinese: '无中线' },
        term_hint: { german: 'Ostasien', english: 'East Asia', spanish: 'Asia Oriental', french: "Asie de l'Est", chinese: '东亚' },
    },
    {
        category: 'Marking',
        countries: ['Peru', 'Ecuador', 'Japan'],
        description: 'No parking zones.',
        term: { german: 'Bordstein (Rot-Weiß)', english: 'Curb (Red-White)', spanish: 'Bordillo (rojo-blanco)', french: 'Bordure (rouge-blanc)', chinese: '路缘（红白）' },
        term_hint: { german: 'Südamerika oder Ostasien', english: 'South America or East Asia', spanish: 'Sudamérica o Asia Oriental', french: "Amérique du Sud ou Asie de l'Est", chinese: '南美或东亚' },
    },
    {
        category: 'Marking',
        countries: ['India', 'Bangladesh', 'UK'],
        description: 'Edge markings.',
        term: { german: 'Bordstein (Gelb-Schwarz)', english: 'Curb (Yellow-Black)', spanish: 'Bordillo (amarillo-negro)', french: 'Bordure (jaune-noir)', chinese: '路缘（黄黑）' },
        term_hint: { german: 'Südasien oder UK', english: 'South Asia or UK', spanish: 'Sur de Asia o Reino Unido', french: 'Asie du Sud ou Royaume-Uni', chinese: '南亚或英国' },
    },
    {
        category: 'Marking',
        countries: ['Italy', 'Spain'],
        description: 'Paid parking zones.',
        term: { german: 'Blaue Parkplätze', english: 'Blue Parking Bays', spanish: 'Plazas de aparcamiento azules', french: 'Places de stationnement bleues', chinese: '蓝色停车位' },
        term_hint: { german: 'Südeuropa', english: 'Southern Europe', spanish: 'Europa del Sur', french: 'Europe du Sud', chinese: '南欧' },
    },
    {
        category: 'Marking',
        countries: ['Denmark', 'Germany'],
        description: 'Colored cycling paths.',
        term: { german: 'Grüner Radweg', english: 'Green Bike Lane', spanish: 'Carril bici verde', french: 'Piste cyclable verte', chinese: '绿色自行车道' },
        term_hint: { german: 'Mittel- oder Nordeuropa', english: 'Central or Northern Europe', spanish: 'Europa Central o del Norte', french: 'Europe centrale ou du Nord', chinese: '中欧或北欧' },
    },
    {
        category: 'Marking',
        countries: ['United Kingdom', 'Australia', 'New Zealand'],
        description: 'Embedded road markers.',
        term: { german: 'Straßenreflektoren', english: "Cat's Eyes (Reflectors)", spanish: 'Ojos de gato (reflectores)', french: 'Plots réfléchissants', chinese: '道路反光钉' },
        term_hint: { german: 'Britischer Einflussbereich', english: 'British influence (UK/Oceania)', spanish: 'Influencia británica (RU/Oceanía)', french: 'Influence britannique (R-U/Océanie)', chinese: '英联邦地区（英国/大洋洲）' },
    },
    {
        category: 'Marking',
        countries: ['Switzerland', 'Iceland'],
        description: 'Zebra crossings painted yellow.',
        term: { german: 'Gelber Zebrastreifen', english: 'Yellow Zebra Crossing', spanish: 'Paso de cebra amarillo', french: 'Passage piéton jaune', chinese: '黄色斑马线' },
        term_hint: { german: 'Europa (Alpen oder hoher Norden)', english: 'Europe (Alps or far North)', spanish: 'Europa (Alpes o extremo norte)', french: 'Europe (Alpes ou grand Nord)', chinese: '欧洲（阿尔卑斯或极北）' },
    },
    {
        category: 'Marking',
        countries: ['Italy', 'Switzerland', 'Croatia'],
        description: 'Common on mountain roads.',
        term: { german: 'Doppelte weiße Mitte', english: 'Double White Center', spanish: 'Doble línea central blanca', french: 'Double ligne centrale blanche', chinese: '双白中线' },
        term_hint: { german: 'Südeuropa (oft gebirgig)', english: 'Southern Europe (often mountainous)', spanish: 'Europa del Sur (a menudo montañosa)', french: 'Europe du Sud (souvent montagneuse)', chinese: '南欧（多山）' },
    },

    // --- NATURE ---
    {
        category: 'Nature',
        countries: ['Brazil', 'Australia', 'Kenya', 'Sri Lanka'],
        description: 'Distinctive iron dirt.',
        term: { german: 'Rote Erde', english: 'Red Soil', spanish: 'Tierra roja', french: 'Terre rouge', chinese: '红土' },
        term_hint: { german: 'Südhalbkugel oder Tropen', english: 'Southern Hemisphere or Tropics', spanish: 'Hemisferio sur o trópicos', french: 'Hémisphère sud ou tropiques', chinese: '南半球或热带' },
    },
    {
        category: 'Nature',
        countries: ['Iceland', 'Spain (Canaries)'],
        description: 'Cooled lava fields.',
        term: { german: 'Vulkangestein', english: 'Volcanic Rock', spanish: 'Roca volcánica', french: 'Roche volcanique', chinese: '火山岩' },
        term_hint: { german: 'Nordeuropa oder subtropische Inseln', english: 'Northern Europe or Subtropical Islands', spanish: 'Europa del Norte o islas subtropicales', french: 'Europe du Nord ou îles subtropicales', chinese: '北欧或亚热带岛屿' },
    },
    {
        category: 'Nature',
        countries: ['Brazil', 'Chile'],
        description: 'Striking pine trees.',
        term: { german: 'Araukarien (Bäume)', english: 'Araucaria (Trees)', spanish: 'Araucarias (árboles)', french: 'Araucarias (arbres)', chinese: '南洋杉' },
        term_hint: { german: 'Südamerika', english: 'South America', spanish: 'América del Sur', french: 'Amérique du Sud', chinese: '南美洲' },
    },
    {
        category: 'Nature',
        countries: ['Senegal', 'Botswana', 'Madagascar'],
        description: 'Massive thick trunks.',
        term: { german: 'Baobabs (Bäume)', english: 'Baobab (Trees)', spanish: 'Baobabs (árboles)', french: 'Baobabs (arbres)', chinese: '猴面包树' },
        term_hint: { german: 'Afrika', english: 'Africa', spanish: 'África', french: 'Afrique', chinese: '非洲' },
    },
    {
        category: 'Nature',
        countries: ['Australia', 'Portugal', 'Spain'],
        description: 'Light bark, hanging leaves.',
        term: { german: 'Eukalyptus', english: 'Eucalyptus', spanish: 'Eucalipto', french: 'Eucalyptus', chinese: '桉树' },
        term_hint: { german: 'Ozeanien oder Iberische Halbinsel', english: 'Oceania or Iberian Peninsula', spanish: 'Oceanía o Península Ibérica', french: 'Océanie ou péninsule Ibérique', chinese: '大洋洲或伊比利亚半岛' },
    },
    {
        category: 'Nature',
        countries: ['Russia', 'Finland', 'Baltics'],
        description: 'Nordic vegetation.',
        term: { german: 'Birkenwald', english: 'Birch Forest', spanish: 'Bosque de abedules', french: 'Forêt de bouleaux', chinese: '桦树林' },
        term_hint: { german: 'Nord- und Osteuropa', english: 'Northern and Eastern Europe', spanish: 'Europa del Norte y del Este', french: "Europe du Nord et de l'Est", chinese: '北欧和东欧' },
    },
    {
        category: 'Nature',
        countries: ['Greece', 'Spain', 'Tunisia'],
        description: 'Mediterranean agriculture.',
        term: { german: 'Olivenhain', english: 'Olive Grove', spanish: 'Olivar', french: 'Oliveraie', chinese: '橄榄园' },
        term_hint: { german: 'Mittelmeerraum', english: 'Mediterranean Region', spanish: 'Región mediterránea', french: 'Région méditerranéenne', chinese: '地中海地区' },
    },
    {
        category: 'Nature',
        countries: ['Indonesia', 'Philippines', 'Vietnam'],
        description: 'Steps on a hillside.',
        term: { german: 'Reisterrassen', english: 'Rice Terraces', spanish: 'Terrazas de arroz', french: 'Rizières en terrasses', chinese: '梯田' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Nature',
        countries: ['Malaysia', 'Indonesia'],
        description: 'Monocultures.',
        term: { german: 'Ölpalmen-Plantage', english: 'Palm Oil Plantation', spanish: 'Plantación de palma aceitera', french: 'Plantation de palmiers à huile', chinese: '油棕种植园' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Nature',
        countries: ['Mexico', 'Peru', 'USA'],
        description: 'Desert vegetation.',
        term: { german: 'Große Kakteen', english: 'Large Cacti', spanish: 'Cactus grandes', french: 'Grands cactus', chinese: '大型仙人掌' },
        term_hint: { german: 'Nord- oder Südamerika (Wüste)', english: 'Americas (Deserts)', spanish: 'América (desiertos)', french: 'Amériques (déserts)', chinese: '美洲（沙漠）' },
    },
    {
        category: 'Nature',
        countries: ['Thailand', 'Vietnam'],
        description: 'Limestone formations.',
        term: { german: 'Karst-Felsen', english: 'Karst Mountains', spanish: 'Montañas kársticas', french: 'Montagnes karstiques', chinese: '喀斯特山' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Nature',
        countries: ['USA (Utah)', 'Australia'],
        description: 'Desert rocks.',
        term: { german: 'Rote Canyons', english: 'Red Rock Canyons', spanish: 'Cañones de roca roja', french: 'Canyons de roche rouge', chinese: '红岩峡谷' },
        term_hint: { german: 'Nordamerika oder Ozeanien', english: 'North America or Oceania', spanish: 'América del Norte u Oceanía', french: 'Amérique du Nord ou Océanie', chinese: '北美或大洋洲' },
    },
    {
        category: 'Nature',
        countries: ['Iceland', 'Faroe Islands', 'Greenland'],
        description: 'Extreme climates.',
        term: { german: 'Moos-Tundra', english: 'Moss Tundra', spanish: 'Tundra de musgo', french: 'Toundra de mousse', chinese: '苔藓苔原' },
        term_hint: { german: 'Weit im Norden Europas', english: 'Far Northern Europe', spanish: 'Extremo norte de Europa', french: "Extrême nord de l'Europe", chinese: '欧洲极北' },
    },
    {
        category: 'Nature',
        countries: ['Cambodia', 'Uganda', 'Ecuador'],
        description: 'Tropical agriculture.',
        term: { german: 'Bananenstauden', english: 'Banana Plants', spanish: 'Plataneras', french: 'Bananiers', chinese: '香蕉树' },
        term_hint: { german: 'Tropen (Afrika, Südamerika oder Südostasien)', english: 'Tropics (Africa, South America, or Southeast Asia)', spanish: 'Trópicos (África, Sudamérica o Sudeste Asiático)', french: 'Tropiques (Afrique, Amérique du Sud ou Asie du Sud-Est)', chinese: '热带（非洲、南美或东南亚）' },
    },
    {
        category: 'Nature',
        countries: ['Canada', 'USA', 'Japan'],
        description: 'Seasonal autumn leaves.',
        term: { german: 'Indian Summer', english: 'Indian Summer', spanish: 'Otoño dorado', french: 'Été indien', chinese: '秋季红叶' },
        term_hint: { german: 'Nordamerika oder Ostasien', english: 'North America or East Asia', spanish: 'América del Norte o Asia Oriental', french: "Amérique du Nord ou Asie de l'Est", chinese: '北美或东亚' },
    },
    {
        category: 'Nature',
        countries: ['New Zealand'],
        description: 'Palm-like ferns.',
        term: { german: 'Baumfarne', english: 'Tree Ferns', spanish: 'Helechos arbóreos', french: 'Fougères arborescentes', chinese: '树蕨' },
        term_hint: { german: 'Ozeanien', english: 'Oceania', spanish: 'Oceanía', french: 'Océanie', chinese: '大洋洲' },
    },

    // --- PLATE ---
    {
        category: 'Plate',
        countries: ['Netherlands', 'Luxembourg', 'Israel', 'Colombia'],
        description: 'Completely yellow front & back.',
        term: { german: 'Kennzeichen: Gelb/Gelb', english: 'Plate: Yellow/Yellow', spanish: 'Matrícula: amarilla/amarilla', french: 'Plaque : jaune/jaune', chinese: '车牌：黄/黄' },
        term_hint: { german: 'Westeuropa, Naher Osten oder Südamerika', english: 'Western Europe, Middle East, or South America', spanish: 'Europa Occidental, Oriente Medio o Sudamérica', french: "Europe de l'Ouest, Moyen-Orient ou Amérique du Sud", chinese: '西欧、中东或南美' },
    },
    {
        category: 'Plate',
        countries: ['United Kingdom', 'France (old)', 'Cyprus'],
        description: 'Front white, rear yellow.',
        term: { german: 'Kennzeichen: Hinten Gelb', english: 'Plate: Yellow Back', spanish: 'Matrícula: trasera amarilla', french: 'Plaque : arrière jaune', chinese: '车牌：后黄' },
        term_hint: { german: 'Westeuropa / Britischer Einfluss', english: 'Western Europe / British Influence', spanish: 'Europa Occidental / influencia británica', french: "Europe de l'Ouest / influence britannique", chinese: '西欧 / 英联邦' },
    },
    {
        category: 'Plate',
        countries: ['Norway'],
        description: 'Commercial vehicles.',
        term: { german: 'Grünes Kennzeichen', english: 'Green License Plate', spanish: 'Matrícula verde', french: 'Plaque verte', chinese: '绿色车牌' },
        term_hint: { german: 'Skandinavien', english: 'Scandinavia', spanish: 'Escandinavia', french: 'Scandinavie', chinese: '斯堪的纳维亚' },
    },
    {
        category: 'Plate',
        countries: ['Italy', 'Albania', 'France'],
        description: 'Euroband left and right.',
        term: { german: 'Kennz.: 2 blaue Streifen', english: 'Plate: 2 Blue Strips', spanish: 'Matrícula: 2 franjas azules', french: 'Plaque : 2 bandes bleues', chinese: '车牌：两条蓝边' },
        term_hint: { german: 'Süd-/Westeuropa', english: 'Southern/Western Europe', spanish: 'Europa del Sur/Oeste', french: 'Europe du Sud/Ouest', chinese: '南欧/西欧' },
    },
    {
        category: 'Plate',
        countries: ['Kyrgyzstan'],
        description: 'Distinctive accent.',
        term: { german: 'Kennzeichen: Rot links', english: 'Plate: Red Left', spanish: 'Matrícula: rojo a la izquierda', french: 'Plaque : rouge à gauche', chinese: '车牌：左侧红' },
        term_hint: { german: 'Zentralasien', english: 'Central Asia', spanish: 'Asia Central', french: 'Asie centrale', chinese: '中亚' },
    },
    {
        category: 'Plate',
        countries: ['Portugal'],
        description: 'Date display on older plates.',
        term: { german: 'Kennzeichen: Gelb rechts', english: 'Plate: Yellow Right', spanish: 'Matrícula: amarillo a la derecha', french: 'Plaque : jaune à droite', chinese: '车牌：右侧黄' },
        term_hint: { german: 'Südwesteuropa', english: 'Southwestern Europe', spanish: 'Europa Suroccidental', french: 'Europe du Sud-Ouest', chinese: '西南欧' },
    },
    {
        category: 'Plate',
        countries: ['Belgium'],
        description: 'Diplomatic or standard BE.',
        term: { german: 'Kennzeichen: Rote Schrift', english: 'Plate: Red Font', spanish: 'Matrícula: letras rojas', french: 'Plaque : texte rouge', chinese: '车牌：红字' },
        term_hint: { german: 'Westeuropa', english: 'Western Europe', spanish: 'Europa Occidental', french: "Europe de l'Ouest", chinese: '西欧' },
    },
    {
        category: 'Plate',
        countries: ['USA', 'Japan', 'Ecuador'],
        description: 'Non-Euro format.',
        term: { german: 'Kurzes Kennzeichen', english: 'Short/Square Plate', spanish: 'Matrícula corta/cuadrada', french: 'Plaque courte/carrée', chinese: '短/方形车牌' },
        term_hint: { german: 'Amerika oder Asien', english: 'Americas or Asia', spanish: 'América o Asia', french: 'Amériques ou Asie', chinese: '美洲或亚洲' },
    },
    {
        category: 'Plate',
        countries: ['Poland', 'Spain', 'Romania'],
        description: 'Euro standard, no extras.',
        term: { german: 'Weißes Euro-Kennzeichen', english: 'White Euro Plate', spanish: 'Matrícula europea blanca', french: 'Plaque euro blanche', chinese: '白色欧盟车牌' },
        term_hint: { german: 'Europa', english: 'Europe', spanish: 'Europa', french: 'Europe', chinese: '欧洲' },
    },
    {
        category: 'Plate',
        countries: ['USA (various states)', 'Canada'],
        description: 'Legal in many US states.',
        term: { german: 'Kein Front-Kennzeichen', english: 'No Front Plate', spanish: 'Sin matrícula delantera', french: 'Pas de plaque avant', chinese: '无前车牌' },
        term_hint: { german: 'Nordamerika', english: 'North America', spanish: 'América del Norte', french: 'Amérique du Nord', chinese: '北美洲' },
    },
    {
        category: 'Plate',
        countries: ['Indonesia', 'Malaysia'],
        description: 'Standard in SEA.',
        term: { german: 'Schwarzes Kennzeichen', english: 'Black License Plate', spanish: 'Matrícula negra', french: 'Plaque noire', chinese: '黑色车牌' },
        term_hint: { german: 'Südostasien', english: 'Southeast Asia', spanish: 'Sudeste Asiático', french: 'Asie du Sud-Est', chinese: '东南亚' },
    },
    {
        category: 'Plate',
        countries: ['India', 'UAE'],
        description: 'Special status.',
        term: { german: 'Rotes Kennzeichen', english: 'Red Diplomatic Plate', spanish: 'Matrícula diplomática roja', french: 'Plaque diplomatique rouge', chinese: '红色外交车牌' },
        term_hint: { german: 'Asien / Naher Osten', english: 'Asia / Middle East', spanish: 'Asia / Oriente Medio', french: 'Asie / Moyen-Orient', chinese: '亚洲/中东' },
    },

    // --- CAMERA ---
    {
        category: 'Camera',
        countries: ['USA', 'Canada', 'Australia', 'South Africa'],
        description: 'Gen 2 camera shadow.',
        term: { german: 'Halo (Himmel)', english: 'Halo (Sky)', spanish: 'Halo (cielo)', french: 'Halo (ciel)', chinese: '光晕（天空）' },
        term_hint: { german: 'Nordamerika, Ozeanien oder Südafrika', english: 'North America, Oceania, or South Africa', spanish: 'América del Norte, Oceanía o Sudáfrica', french: 'Amérique du Nord, Océanie ou Afrique du Sud', chinese: '北美、大洋洲或南非' },
    },
    {
        category: 'Camera',
        countries: ['Japan', 'Switzerland'],
        description: 'Eye-level with cars.',
        term: { german: 'Niedrige Kamera', english: 'Low Camera', spanish: 'Cámara baja', french: 'Caméra basse', chinese: '低机位' },
        term_hint: { german: 'Ostasien oder Mitteleuropa', english: 'East Asia or Central Europe', spanish: 'Asia Oriental o Europa Central', french: "Asie de l'Est ou Europe centrale", chinese: '东亚或中欧' },
    },
    {
        category: 'Camera',
        countries: ['South Korea', 'Taiwan'],
        description: 'Gen 4 artifact.',
        term: { german: 'Lila Farbstich', english: 'Purple Tint', spanish: 'Tinte púrpura', french: 'Teinte violette', chinese: '紫色色调' },
        term_hint: { german: 'Ostasien', english: 'East Asia', spanish: 'Asia Oriental', french: "Asie de l'Est", chinese: '东亚' },
    },
    {
        category: 'Camera',
        countries: ['Nigeria'],
        description: 'Spots on the lens.',
        term: { german: 'Kamera-Konfetti', english: 'Camera Dirt (Confetti)', spanish: 'Suciedad en la lente (confeti)', french: "Saleté sur l'objectif (confettis)", chinese: '镜头污点（彩纸状）' },
        term_hint: { german: 'Westafrika', english: 'West Africa', spanish: 'África Occidental', french: "Afrique de l'Ouest", chinese: '西非' },
    },
    {
        category: 'Camera',
        countries: ['Venice', 'National Parks'],
        description: 'Pedestrian with backpack.',
        term: { german: 'Trekker-Schatten', english: 'Trekker Shadow', spanish: 'Sombra del trekker', french: 'Ombre du trekker', chinese: '背包相机阴影' },
        term_hint: { german: 'Orte ohne Autos (Altstädte/Parks)', english: 'Car-free zones (Old towns/Parks)', spanish: 'Zonas sin coches (cascos antiguos/parques)', french: 'Zones sans voitures (vieilles villes/parcs)', chinese: '无车区（老城/公园）' },
    },
    {
        category: 'Camera',
        countries: ['Bulgaria', 'Hungary', 'Finland'],
        description: 'Seasonal coverage.',
        term: { german: 'Winter / Schnee', english: 'Winter / Snow', spanish: 'Invierno / nieve', french: 'Hiver / neige', chinese: '冬季 / 积雪' },
        term_hint: { german: 'Osteuropa oder Skandinavien', english: 'Eastern Europe or Scandinavia', spanish: 'Europa del Este o Escandinavia', french: "Europe de l'Est ou Scandinavie", chinese: '东欧或斯堪的纳维亚' },
    },
    {
        category: 'Camera',
        countries: ['Greenland', 'Amazon (Brazil)'],
        description: 'Water Street View.',
        term: { german: 'Boot-Aufnahme', english: 'Boat Footage', spanish: 'Grabación desde barco', french: 'Prise de vue en bateau', chinese: '船拍画面' },
        term_hint: { german: 'Arktis oder Südamerika (Flüsse)', english: 'Arctic or South America (Rivers)', spanish: 'Ártico o Sudamérica (ríos)', french: 'Arctique ou Amérique du Sud (fleuves)', chinese: '北极或南美（河流）' },
    },
    {
        category: 'Camera',
        countries: ['Russia', 'Poland', 'United Kingdom'],
        description: 'Bad weather driving.',
        term: { german: 'Overcast (Düster)', english: 'Overcast (Gloomy)', spanish: 'Cielo nublado (gris)', french: 'Ciel couvert (gris)', chinese: '阴天（灰暗）' },
        term_hint: { german: 'Nord- oder Osteuropa', english: 'Northern or Eastern Europe', spanish: 'Europa del Norte o del Este', french: "Europe du Nord ou de l'Est", chinese: '北欧或东欧' },
    },
    {
        category: 'Camera',
        countries: ['South Africa', 'Mexico'],
        description: 'Late afternoon coverage.',
        term: { german: 'Golden Hour', english: 'Golden Hour', spanish: 'Hora dorada', french: 'Heure dorée', chinese: '黄金时刻' },
        term_hint: { german: 'Südliches Afrika oder Zentralamerika', english: 'Southern Africa or Central America', spanish: 'África Austral o América Central', french: 'Afrique australe ou Amérique centrale', chinese: '南部非洲或中美洲' },
    },
    {
        category: 'Camera',
        countries: ['Qatar', 'UAE'],
        description: 'Giant black blur at bottom.',
        term: { german: 'Zensur-Kreis (unten)', english: 'Censorship Circle', spanish: 'Círculo de censura', french: 'Cercle de censure', chinese: '审查黑圈' },
        term_hint: { german: 'Naher Osten', english: 'Middle East', spanish: 'Oriente Medio', french: 'Moyen-Orient', chinese: '中东' },
    },
    {
        category: 'Camera',
        countries: ['Various Landmarks'],
        description: 'Aerial view.',
        term: { german: 'Drohnen-Schatten', english: 'Drone Shadow', spanish: 'Sombra de dron', french: 'Ombre de drone', chinese: '无人机阴影' },
        term_hint: { german: 'Oft bei Denkmälern/Parks', english: 'Often near monuments or parks', spanish: 'A menudo cerca de monumentos o parques', french: 'Souvent près de monuments ou parcs', chinese: '常见于纪念碑或公园附近' },
    },
];
